//! Shell-output transport decoding for agent actions.
//!
//! Pane shell transactions can wrap command output in Mezzanine base64 markers
//! so model-facing action results receive clean UTF-8 text rather than shell
//! wrapper scaffolding. This module keeps that decoding separate from turn
//! execution and action-result construction.

use super::super::shell::{SHELL_OUTPUT_BASE64_BEGIN_MARKER, SHELL_OUTPUT_BASE64_END_MARKER};
use super::result_context::shell_output_line_is_mezzanine_wrapper;
use base64::Engine;

/// Decodes shell-output transport blocks emitted by non-stateful transactions.
///
/// # Parameters
/// - `stdout`: Bounded raw PTY observation for one shell transaction.
pub fn decode_shell_output_transport(stdout: &str) -> String {
    decode_base64_transport_output(
        stdout,
        SHELL_OUTPUT_BASE64_BEGIN_MARKER,
        SHELL_OUTPUT_BASE64_END_MARKER,
        "shell output",
    )
}

/// Decodes one marker-bounded base64 transport stream while preserving useful
/// text outside the markers.
fn decode_base64_transport_output(stdout: &str, begin: &str, end: &str, label: &str) -> String {
    if !stdout.contains(begin) {
        return stdout.to_string();
    }
    let normalized = stdout.replace("\r\n", "\n").replace('\r', "\n");
    let mut decoded = String::new();
    let mut block = String::new();
    let mut outside_block = String::new();
    let mut in_block = false;
    for line in normalized.split_inclusive('\n') {
        let marker_candidate = line.trim_end_matches('\n');
        if marker_candidate == begin {
            append_non_wrapper_transport_text(&mut decoded, &outside_block);
            outside_block.clear();
            in_block = true;
            block.clear();
            continue;
        }
        if marker_candidate == end {
            decoded.push_str(&decode_base64_transport_block(&block, label, false));
            in_block = false;
            block.clear();
            continue;
        }
        if in_block {
            block.push_str(marker_candidate.trim());
        } else {
            outside_block.push_str(line);
        }
    }
    if in_block {
        decoded.push_str(&decode_base64_transport_block(&block, label, true));
        decoded.push_str(&format!(
            "[mez: {label} base64 transport ended before end marker]\n"
        ));
    } else {
        append_non_wrapper_transport_text(&mut decoded, &outside_block);
    }
    decoded
}

/// Appends useful non-wrapper text found outside a base64 transport block.
fn append_non_wrapper_transport_text(decoded: &mut String, text: &str) {
    for line in text.split_inclusive('\n') {
        let (line, had_newline) = line
            .strip_suffix('\n')
            .map(|line| (line, true))
            .unwrap_or((line, false));
        let trimmed = line.trim();
        if trimmed.is_empty()
            || shell_output_line_is_mezzanine_wrapper(trimmed)
            || shell_output_line_is_mezzanine_transport_scaffold(trimmed)
        {
            continue;
        }
        decoded.push_str(line);
        if had_newline {
            decoded.push('\n');
        }
    }
}

/// Reports whether a line is shell block syntax generated by the wrapper.
///
/// Only filters unambiguous wrapping tokens (`{`, `}`, `done`) that are
/// shell block-syntax artifacts. The previous set also included `C`, `I`,
/// `o`, `SY`, `TC`, `PS0`, and `-`, which are common in legitimate
/// command output (JSON, markdown lists, single-letter C/I output, diff
/// hunks, etc.) and were silently dropped.
fn shell_output_line_is_mezzanine_transport_scaffold(trimmed: &str) -> bool {
    matches!(trimmed, "{" | "}" | "done")
}

/// Decodes one base64 transport block into UTF-8 model-facing text.
fn decode_base64_transport_block(block: &str, label: &str, partial: bool) -> String {
    let mut cleaned = block
        .chars()
        .filter(|character| !character.is_whitespace())
        .collect::<String>();
    if partial {
        let full_quartets = cleaned.len() - (cleaned.len() % 4);
        cleaned.truncate(full_quartets);
    }
    if cleaned.is_empty() {
        return String::new();
    }
    match base64::engine::general_purpose::STANDARD.decode(cleaned.as_bytes()) {
        Ok(bytes) => match String::from_utf8(bytes) {
            Ok(text) => text,
            Err(error) => {
                let bytes = error.into_bytes();
                let mut text = format!(
                    "[mez: {label} contained non-UTF-8 bytes; decoded {} bytes with replacement characters]\n",
                    bytes.len()
                );
                text.push_str(&String::from_utf8_lossy(&bytes));
                text
            }
        },
        Err(error) => format!("[mez: failed to decode {label} base64 transport: {error}]\n"),
    }
}
