//! Cli Env implementation.
//!
//! This module owns the cli env boundary for Mezzanine. It keeps related
//! state transitions and helper routines localized so neighboring modules
//! interact through typed APIs instead of duplicating subsystem details.

use std::os::fd::RawFd;

use super::{
    Args, CliOutputFormat, DEFAULT_SOCKET_NAME, MEZ_ENV_FIELD_SEPARATOR, MezError, OsString,
    Parser, PathBuf, Result, RuntimeEnv, Subcommand, default_socket_directory,
    socket_path_for_name,
};
use crate::host::terminal::read_attached_terminal_size;

// Socket selection, invocation parsing, and CLI option helpers.

/// Carries Socket Selection state for this subsystem.
///
/// The type keeps related data explicit so callers can inspect and move
/// structured runtime state without parsing display text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) enum SocketSelection {
    /// Represents the Default case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    Default(PathBuf),
    /// Represents the Explicit case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    Explicit(PathBuf),
    /// Represents the Named case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    Named(PathBuf),
    /// Represents the In Pane case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    InPane(PathBuf),
}

/// Top-level process CLI commands accepted by `mez`.
///
/// This enum is the process-argv command surface. Interactive shell commands
/// and agent slash commands intentionally use separate parsers.
#[derive(Debug, Clone, Subcommand)]
pub(super) enum CliCommand {
    /// Manages Mezzanine configuration.
    Config(super::config::ConfigCliArgs),
    /// Starts a background session daemon and attaches when interactive.
    #[command(visible_alias = "new-session")]
    New(super::serve::NewCliArgs),
    /// Starts a foreground control daemon for a new session.
    #[command(visible_alias = "daemon")]
    Serve(super::serve::ServeCliArgs),
    /// Lists resumable sessions known to this client.
    #[command(visible_alias = "list-sessions")]
    List,
    /// Reattaches the primary terminal or requests observer access.
    #[command(visible_alias = "attach-session")]
    Attach(super::attach::AttachCliArgs),
    /// Detaches the current or specified control client.
    #[command(visible_alias = "detach-client")]
    Detach(DetachCliArgs),
    /// Terminates a live session through the control socket.
    KillSession(KillSessionCliArgs),
    /// Manages persisted snapshots.
    Snapshot(super::snapshot::SnapshotCliArgs),
    /// Manages provider authentication.
    Auth(super::auth::AuthCliArgs),
    /// Manages MCP server configuration.
    Mcp(super::mcp::McpCliArgs),
    /// Manages local project issues.
    Issue(super::issue::IssueCliArgs),
    /// Manages persistent agent memory.
    Memory(super::memory::MemoryCliArgs),
    /// Prints version information.
    Version,
}

/// Carries Cli Invocation state for this subsystem.
///
/// The type keeps related data explicit so callers can inspect and move
/// structured runtime state without parsing display text.
#[derive(Debug, Clone)]
pub(super) struct CliInvocation {
    /// Stores the command value for this data structure.
    ///
    /// The field is part of the structured state exchanged across this module
    /// boundary and should remain aligned with the owning type invariant.
    pub(super) command: Option<CliCommand>,
    /// Stores the socket selection value for this data structure.
    ///
    /// The field is part of the structured state exchanged across this module
    /// boundary and should remain aligned with the owning type invariant.
    pub(super) socket_selection: SocketSelection,
    /// Stores the output format value for this data structure.
    ///
    /// The field is part of structured state exchanged across this module
    /// boundary and should remain aligned with the owning type invariant.
    pub(super) output_format: CliOutputFormat,
}

/// Represents a process argv parse result that either produced an invocation
/// or a clap-rendered informational response.
#[derive(Debug, Clone)]
pub(super) enum CliInvocationParse {
    /// A runnable command invocation.
    Invocation(Box<CliInvocation>),
    /// A help or version response generated by clap.
    Display(String),
}

#[derive(Debug, Parser)]
#[command(
    name = "mez",
    version,
    about = "Terminal workspace and agent muxxer.",
    long_about = None,
    disable_help_subcommand = false
)]
/// Carries Cli Argv state for this subsystem.
///
/// The type keeps related data explicit so callers can inspect and move
/// structured runtime state without parsing display text.
pub(super) struct CliArgv {
    /// Selects an explicit control socket path.
    #[arg(
        short = 'S',
        value_name = "PATH",
        global = true,
        help_heading = "Global Options"
    )]
    pub(super) socket: Option<PathBuf>,
    /// Selects a named socket under the runtime directory.
    #[arg(
        short = 'L',
        value_name = "NAME",
        global = true,
        help_heading = "Global Options"
    )]
    pub(super) socket_name: Option<String>,
    /// Emits machine-readable JSON for structured command output.
    #[arg(long, global = true, help_heading = "Global Options")]
    pub(super) json: bool,
    /// Optional process command.
    #[command(subcommand)]
    pub(super) command: Option<CliCommand>,
}

/// Typed process CLI arguments for `mez detach`.
#[derive(Debug, Clone, Args)]
pub(super) struct DetachCliArgs {
    /// Control client id to detach instead of the current client.
    #[arg(long, value_name = "ID")]
    pub(super) client_id: Option<String>,
}

/// Typed process CLI arguments for `mez kill-session`.
#[derive(Debug, Clone, Args)]
pub(super) struct KillSessionCliArgs {
    /// Confirms intentional termination of the live session.
    #[arg(short, long)]
    pub(super) force: bool,
}

impl CliInvocation {
    /// Runs the parse operation for this subsystem.
    ///
    /// The function keeps parsing, state changes, and error propagation in
    /// the owning module so callers receive typed results instead of relying
    /// on duplicated control-flow logic.
    #[cfg(test)]
    pub(super) fn parse(
        args: &[String],
        runtime: &RuntimeEnv,
        mez: Option<&OsString>,
    ) -> Result<Self> {
        match Self::parse_or_display(args, runtime, mez)? {
            CliInvocationParse::Invocation(invocation) => Ok(*invocation),
            CliInvocationParse::Display(display) => Err(MezError::invalid_args(display)),
        }
    }

    /// Parses the process argv and preserves clap-rendered help/version
    /// responses as a successful display outcome.
    ///
    /// # Parameters
    /// - `args`: The process argv beginning with the executable name.
    /// - `runtime`: Runtime environment used for default socket selection.
    /// - `mez`: Optional in-pane environment value.
    pub(super) fn parse_or_display(
        args: &[String],
        runtime: &RuntimeEnv,
        mez: Option<&OsString>,
    ) -> Result<CliInvocationParse> {
        let mut socket_selection = None;
        let parsed = match CliArgv::try_parse_from(args) {
            Ok(parsed) => parsed,
            Err(error)
                if matches!(
                    error.kind(),
                    clap::error::ErrorKind::DisplayHelp | clap::error::ErrorKind::DisplayVersion
                ) =>
            {
                return Ok(CliInvocationParse::Display(error.to_string()));
            }
            Err(error) => return Err(MezError::invalid_args(error.to_string())),
        };

        if let Some(socket_path) = parsed.socket {
            if !socket_path.is_absolute() {
                return Err(MezError::invalid_args(
                    "-S requires an absolute socket path",
                ));
            }
            socket_selection = Some(set_socket_selection(
                socket_selection,
                SocketSelection::Explicit(socket_path),
            )?);
        }
        if let Some(name) = parsed.socket_name {
            let directory = default_socket_directory(runtime)?;
            let socket_path = socket_path_for_name(&directory.path, &name)?;
            socket_selection = Some(set_socket_selection(
                socket_selection,
                SocketSelection::Named(socket_path),
            )?);
        }

        let socket_selection = match socket_selection {
            Some(selection) => selection,
            None => match socket_selection_from_mez(mez)? {
                Some(selection) => selection,
                None => default_socket_selection(runtime)?,
            },
        };

        Ok(CliInvocationParse::Invocation(Box::new(Self {
            command: parsed.command,
            socket_selection,
            output_format: CliOutputFormat::from_json_flag(parsed.json),
        })))
    }
}

/// Renders clap help for one process CLI command path.
///
/// # Parameters
/// - `path`: Command names from the top-level command down to the target.
pub(super) fn render_cli_help(path: &[&str]) -> Result<String> {
    let argv = std::iter::once("mez".to_string())
        .chain(path.iter().map(|part| (*part).to_string()))
        .chain(std::iter::once("--help".to_string()));
    match CliArgv::try_parse_from(argv) {
        Err(error) if matches!(error.kind(), clap::error::ErrorKind::DisplayHelp) => {
            Ok(error.to_string())
        }
        Err(error) => Err(MezError::invalid_args(error.to_string())),
        Ok(_) => Err(MezError::invalid_state(
            "clap did not render help for a requested command path",
        )),
    }
}

/// Renders clap version output for the process CLI.
pub(super) fn render_cli_version() -> Result<String> {
    match CliArgv::try_parse_from(["mez", "--version"]) {
        Err(error) if matches!(error.kind(), clap::error::ErrorKind::DisplayVersion) => {
            Ok(error.to_string())
        }
        Err(error) => Err(MezError::invalid_args(error.to_string())),
        Ok(_) => Err(MezError::invalid_state(
            "clap did not render version for the process CLI",
        )),
    }
}

/// Runs the default socket selection operation for this subsystem.
///
/// The function keeps parsing, state changes, and error propagation in
/// the owning module so callers receive typed results instead of relying
/// on duplicated control-flow logic.
pub(super) fn default_socket_selection(runtime: &RuntimeEnv) -> Result<SocketSelection> {
    let directory = default_socket_directory(runtime)?;
    Ok(SocketSelection::Default(socket_path_for_name(
        &directory.path,
        DEFAULT_SOCKET_NAME,
    )?))
}

/// Runs the socket selection from mez operation for this subsystem.
///
/// The function keeps parsing, state changes, and error propagation in
/// the owning module so callers receive typed results instead of relying
/// on duplicated control-flow logic.
pub(super) fn socket_selection_from_mez(
    value: Option<&OsString>,
) -> Result<Option<SocketSelection>> {
    let Some(value) = value else {
        return Ok(None);
    };
    let value = value.to_string_lossy();
    if value.trim().is_empty() {
        return Ok(None);
    }
    let socket = value
        .split(MEZ_ENV_FIELD_SEPARATOR)
        .next()
        .unwrap_or_default()
        .trim();
    if socket.is_empty() {
        return Ok(None);
    }
    let path = PathBuf::from(socket);
    if !path.is_absolute() {
        return Err(MezError::invalid_args(
            "MEZ contains a relative socket path",
        ));
    }
    Ok(Some(SocketSelection::InPane(path)))
}

/// Runs the set socket selection operation for this subsystem.
///
/// The function keeps parsing, state changes, and error propagation in
/// the owning module so callers receive typed results instead of relying
/// on duplicated control-flow logic.
pub(super) fn set_socket_selection(
    existing: Option<SocketSelection>,
    next: SocketSelection,
) -> Result<SocketSelection> {
    if existing.is_some() {
        Err(MezError::invalid_args(
            "only one control socket selector may be provided",
        ))
    } else {
        Ok(next)
    }
}
/// Runs the terminal size from environment operation for this subsystem.
///
/// The function keeps parsing, state changes, and error propagation in
/// the owning module so callers receive typed results instead of relying
/// on duplicated control-flow logic.
pub(super) fn terminal_size_from_environment() -> (u16, u16) {
    let columns = std::env::var("COLUMNS")
        .ok()
        .and_then(|value| value.parse::<u16>().ok())
        .filter(|value| *value > 0)
        .unwrap_or(80);
    let rows = std::env::var("LINES")
        .ok()
        .and_then(|value| value.parse::<u16>().ok())
        .filter(|value| *value > 0)
        .unwrap_or(24);
    (columns, rows)
}

/// Returns the live terminal size from a TTY file descriptor when available,
/// falling back to shell-provided `COLUMNS`/`LINES` and finally 80x24.
///
/// Default `mez` launch starts a background daemon before attaching the primary
/// client, so the daemon cannot query the parent terminal itself. The attach
/// side must prefer the real TTY size for `control/initialize` so the initial
/// pane is resized before its first user-facing render.
pub(super) fn terminal_size_from_fd_or_environment(fd: Option<RawFd>) -> (u16, u16) {
    if let Some(fd) = fd
        && let Ok(Some(size)) = read_attached_terminal_size(fd)
    {
        return (size.columns, size.rows);
    }
    terminal_size_from_environment()
}

/// Runs the selected socket path operation for this subsystem.
///
/// The function keeps parsing, state changes, and error propagation in
/// the owning module so callers receive typed results instead of relying
/// on duplicated control-flow logic.
pub(super) fn selected_socket_path(socket_selection: &SocketSelection) -> &PathBuf {
    match socket_selection {
        SocketSelection::Default(path)
        | SocketSelection::Explicit(path)
        | SocketSelection::Named(path)
        | SocketSelection::InPane(path) => path,
    }
}

/// Runs the cli idempotency key operation for this subsystem.
///
/// The function keeps parsing, state changes, and error propagation in
/// the owning module so callers receive typed results instead of relying
/// on duplicated control-flow logic.
pub(super) fn cli_idempotency_key(operation: &str) -> String {
    format!("cli-{}-{operation}", std::process::id())
}
/// Runs the registry root operation for this subsystem.
///
/// The function keeps parsing, state changes, and error propagation in
/// the owning module so callers receive typed results instead of relying
/// on duplicated control-flow logic.
pub(super) fn registry_root(socket_selection: &SocketSelection) -> Result<PathBuf> {
    let socket_path = match socket_selection {
        SocketSelection::Default(path)
        | SocketSelection::Explicit(path)
        | SocketSelection::Named(path)
        | SocketSelection::InPane(path) => path,
    };
    socket_path
        .parent()
        .map(PathBuf::from)
        .ok_or_else(|| MezError::invalid_args("control socket path must have a parent directory"))
}
