[package]
name = "mez-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
description = "Stable low-dependency contracts shared by Mezzanine crates"
documentation.workspace = true
homepage.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
