//! Semantic MAAP action lowering.
//!
//! Models author MAAP actions such as `shell_command` and `apply_patch`. This
//! module owns deterministic conversion from those actions into runtime
//! execution plans. Local actions are expressed as pane shell transactions so
//! they operate inside the same local, remote, or container shell the user is
//! interacting with through Mezzanine.

mod patch;

use super::Result;
use super::maap::{AgentAction, AgentActionPayload};
use super::shell::validate_agent_authored_shell_command;

#[cfg(test)]
pub(super) use patch::APPLY_PATCH_TIMEOUT_MS;
pub use patch::{
    ApplyPatchTransactionPhase, apply_patch_error_plan, apply_patch_touched_paths,
    apply_patch_transaction_phase, apply_patch_write_plan_from_read_output,
    try_convert_unified_diff_to_mez_patch,
};

/// Runtime-generated shell execution data for one local action.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalActionPlan {
    /// Concise user-facing summary shown before the action executes.
    pub summary: String,
    /// Exact pane shell input generated by Mezzanine.
    pub command: String,
    /// Classifier-friendly command representing the same broad effect.
    pub policy_command: String,
    /// Whether the generated shell command expects direct user interaction.
    pub interactive: bool,
    /// Whether the generated shell command should run in the live pane shell.
    pub stateful: bool,
    /// Optional timeout for the generated shell command.
    pub timeout_ms: Option<u64>,
    /// Whether normal agent mode should show the command's cleaned output after
    /// successful completion even though raw shell output is otherwise hidden.
    pub display_output_after_completion: bool,
}

/// Returns the local shell plan for a shell-backed MAAP action.
pub fn local_action_plan(action: &AgentAction) -> Result<Option<LocalActionPlan>> {
    match &action.payload {
        AgentActionPayload::ShellCommand {
            summary,
            command,
            interactive,
            stateful,
            timeout_ms,
        } => {
            validate_agent_authored_shell_command(command)?;
            Ok(Some(LocalActionPlan {
                summary: summary.clone(),
                command: command.clone(),
                policy_command: command.clone(),
                interactive: *interactive,
                stateful: *stateful,
                timeout_ms: *timeout_ms,
                display_output_after_completion: false,
            }))
        }
        AgentActionPayload::ApplyPatch { patch, strip } => {
            Ok(Some(patch::apply_patch_plan(patch, *strip)?))
        }
        _ => Ok(None),
    }
}

/// Returns the user-facing summary for a shell-backed action.
pub fn local_action_summary(action: &AgentAction) -> Result<Option<String>> {
    Ok(local_action_plan(action)?.map(|plan| plan.summary))
}

/// Returns true when an action is implemented by a pane shell transaction.
pub fn action_is_local_shell_backed(action: &AgentAction) -> bool {
    matches!(
        action.payload,
        AgentActionPayload::ShellCommand { .. } | AgentActionPayload::ApplyPatch { .. }
    )
}
