//! Persistent agent-child handoff and parent-owned return boundaries.
//!
//! The parent emits its opaque exit marker only after synchronous child teardown
//! and history/option restoration. Managed startup state stays runtime-owned;
//! this module renders source but never launches a process or writes pane input.

use super::*;

/// Renders the shell line used to enter an agent-mode subshell.
///
/// The command starts the configured shell in the pane's current working
/// directory and resumes the parent shell only after the child exits. The
/// parent wrapper suppresses shell history before launching the child so the
/// Mezzanine-owned handoff does not persist in the user's normal history. It
/// defines the handoff as a multiline function before invoking it, keeping
/// physical terminal lines within the canonical-input limits of Unix PTYs
/// while ensuring the parent parses cleanup before the child can consume input.
pub fn agent_subshell_enter_command(
    shell_path: &Path,
    classification: ShellClassification,
) -> AgentShellValidationResult<String> {
    agent_subshell_enter_command_with_zsh_history_token(shell_path, classification, None)
}

/// Renders an agent-mode subshell handoff with optional managed zsh history isolation.
///
/// The token must match the pane startup hook. When present for zsh, the
/// complete parent-shell transport enters a private history frame before any
/// wrapper records are submitted and restores the prior frame after the child
/// shell exits.
pub fn agent_subshell_enter_command_with_zsh_history_token(
    shell_path: &Path,
    classification: ShellClassification,
    zsh_history_token: Option<&MarkerToken>,
) -> AgentShellValidationResult<String> {
    agent_subshell_enter_command_with_shell_compatibility(
        shell_path,
        classification,
        zsh_history_token,
        None,
        None,
    )
}

/// Renders an agent-mode subshell handoff with managed shell startup state.
///
/// The optional Bash receiver rcfile is retained only for a pane that owns the
/// private receiver. Callers without that pane-scoped compatibility state keep
/// the normal startup-suppressed Bash child behavior.
pub fn agent_subshell_enter_command_with_shell_compatibility(
    shell_path: &Path,
    classification: ShellClassification,
    zsh_history_token: Option<&MarkerToken>,
    bash_receiver_rcfile: Option<&Path>,
    bash_receiver_install_marker: Option<&str>,
) -> AgentShellValidationResult<String> {
    agent_subshell_enter_command_with_shell_compatibility_and_exit_marker(
        shell_path,
        classification,
        zsh_history_token,
        None,
        bash_receiver_rcfile,
        bash_receiver_install_marker,
        None,
        None,
        None,
    )
}

/// Returns the opaque terminal bytes emitted after an agent subshell exits.
///
/// The marker is generated by the runtime for one pane handoff and written by
/// the parent shell only after child-shell cleanup has completed.
pub fn agent_subshell_exit_marker_bytes(marker: &MarkerToken) -> Vec<u8> {
    format!("\x1b]133;mez_agent_subshell_exit={}\x1b\\", marker.as_str()).into_bytes()
}

/// Returns the fixed editor-independent input bound to managed Fish child exit.
///
/// The generated child installs this sequence in every supported Fish keymap,
/// so runtime does not depend on whether the user selected Emacs or vi editing.
pub fn fish_agent_subshell_exit_input() -> &'static [u8] {
    b"\x18"
}

/// Renders the shell command that emits one parent-owned subshell exit marker.
fn agent_subshell_exit_marker_command(marker: &MarkerToken) -> String {
    format!(
        "printf '\\033]133;mez_agent_subshell_exit={}\\033\\\\'\n",
        marker.as_str()
    )
}

/// Renders an agent-mode subshell handoff with an optional parent-owned exit boundary.
///
/// When supplied, `exit_marker` is emitted by the parent shell only after the
/// child shell and all handoff cleanup have completed. Runtime output filters
/// use that opaque boundary to distinguish child teardown from the restored
/// parent prompt without relying on shell-specific exit text.
#[allow(clippy::too_many_arguments)]
pub fn agent_subshell_enter_command_with_shell_compatibility_and_exit_marker(
    shell_path: &Path,
    classification: ShellClassification,
    zsh_history_token: Option<&MarkerToken>,
    managed_zsh: Option<&ManagedZshShell>,
    bash_receiver_rcfile: Option<&Path>,
    bash_receiver_install_marker: Option<&str>,
    fish_receiver_install: Option<(&MarkerToken, &str)>,
    zsh_receiver_install_marker: Option<&str>,
    exit_marker: Option<&MarkerToken>,
) -> AgentShellValidationResult<String> {
    if !shell_path.is_absolute() {
        return Err(AgentShellValidationError::invalid_args(
            "agent subshell requires an absolute resolved shell path",
        ));
    }
    let shell = shell_path.to_string_lossy();
    let direct_source_exit_boundary = exit_marker
        .map(agent_subshell_exit_marker_command)
        .unwrap_or_default();
    let source = if classification == ShellClassification::Fish {
        let env_words = fish_agent_subshell_env_word_list().join(" \\\n  ");
        let shell_invocation =
            fish_shell_interactive_invocation_words(&shell, classification, fish_receiver_install);
        format!(
            "begin
{history_start}
if test -n \"$MEZ_SHELL_STTY_STATE\"; stty \"$MEZ_SHELL_STTY_STATE\" 2>/dev/null; or true; end
command env \\
  {env_words} \\
  {shell_invocation}
{history_restore}
{direct_source_exit_boundary}\
end
",
            history_start = fish_shell_history_suppression_start(),
            history_restore = fish_shell_history_restore(),
            direct_source_exit_boundary = direct_source_exit_boundary,
            env_words = env_words,
            shell_invocation = shell_invocation,
        )
    } else if classification == ShellClassification::Zsh && zsh_history_token.is_some() {
        let mut env_words = managed_zsh.map_or_else(
            || posix_agent_subshell_env_word_list_for_classification(classification),
            managed_zsh_agent_subshell_env_word_list,
        );
        if let Some(marker) = zsh_receiver_install_marker {
            env_words.push(format!(
                "MEZ_ZSH_RECEIVER_INSTALL_MARKER={}",
                shell_quote(marker)
            ));
        }
        let env_words = env_words.join(" \\\n  ");
        let shell_invocation = managed_zsh.map_or_else(
            || {
                posix_shell_interactive_invocation_words_with_startup_suppression(
                    &shell,
                    classification,
                    false,
                )
            },
            |_| managed_zsh_interactive_invocation_words(&shell),
        );
        format!(
            "{history_start}__mez_agent_subshell_handoff() {{
if [ -n \"$MEZ_SHELL_STTY_STATE\" ]; then stty \"$MEZ_SHELL_STTY_STATE\" 2>/dev/null || :; fi
unset MEZ_SHELL_STTY_STATE
command env \\
  {env_words} \\
  {shell_invocation}
:
}}
__mez_agent_subshell_handoff; unset -f __mez_agent_subshell_handoff 2>/dev/null || :
{history_finish}{errexit_restore}
{direct_source_exit_boundary}\
",
            history_start = zsh_shell_history_suppression_start(),
            history_finish = zsh_shell_history_marker_finish_prefix(zsh_history_token),
            errexit_restore = posix_shell_errexit_restore_suffix(),
            direct_source_exit_boundary = direct_source_exit_boundary,
            env_words = env_words,
            shell_invocation = shell_invocation,
        )
    } else {
        let env_words = posix_agent_subshell_env_word_list().join(" \\\n  ");
        let shell_invocation = posix_shell_interactive_invocation_words_with_bash_receiver(
            &shell,
            classification,
            bash_receiver_rcfile,
            bash_receiver_install_marker,
        );
        let managed_bash =
            classification == ShellClassification::Bash && bash_receiver_rcfile.is_some();
        let history_start = if managed_bash {
            posix_shell_state_suppression_start()
        } else {
            posix_shell_history_suppression_start()
        };
        let history_cleanup = if managed_bash {
            "MEZ_RESTORE_ERREXIT_NOW=$MEZ_RESTORE_ERREXIT\n\
MEZ_RESTORE_NOUNSET_NOW=$MEZ_RESTORE_NOUNSET\n\
unset MEZ_RESTORE_ERREXIT MEZ_RESTORE_NOUNSET"
        } else {
            "if [ \"$MEZ_HISTORY_HISTFILE_WAS_SET\" = 1 ]; then HISTFILE=$MEZ_HISTORY_HISTFILE_SAVED; else unset HISTFILE; fi\n\
MEZ_RESTORE_HISTORY_NOW=$MEZ_HISTORY_RESTORE\n\
MEZ_RESTORE_ERREXIT_NOW=$MEZ_RESTORE_ERREXIT\n\
MEZ_RESTORE_NOUNSET_NOW=$MEZ_RESTORE_NOUNSET\n\
unset MEZ_HISTORY_RESTORE MEZ_HISTORY_HISTFILE_WAS_SET MEZ_HISTORY_HISTFILE_SAVED MEZ_RESTORE_ERREXIT MEZ_RESTORE_NOUNSET"
        };
        let history_restore = if managed_bash {
            ""
        } else {
            "if [ \"${MEZ_RESTORE_HISTORY_NOW:-0}\" = 1 ]; then set -o history 2>/dev/null || :; fi\n"
        };
        format!(
            "{history_start}__mez_agent_subshell_handoff() {{
if [ -n \"$MEZ_SHELL_STTY_STATE\" ]; then stty \"$MEZ_SHELL_STTY_STATE\" 2>/dev/null || :; fi
unset MEZ_SHELL_STTY_STATE
command env \\
  {env_words} \\
  {shell_invocation}
:
}}
__mez_agent_subshell_cleanup() {{
{history_cleanup}
:
}}
__mez_agent_subshell_restore_options() {{
{history_restore}MEZ_RESTORE_ERREXIT_APPLY=${{MEZ_RESTORE_ERREXIT_NOW:-0}}
MEZ_RESTORE_NOUNSET_APPLY=${{MEZ_RESTORE_NOUNSET_NOW:-0}}
unset MEZ_RESTORE_HISTORY_NOW MEZ_RESTORE_ERREXIT_NOW MEZ_RESTORE_NOUNSET_NOW
case \"$MEZ_RESTORE_ERREXIT_APPLY\" in 1) set -e;; esac
case \"$MEZ_RESTORE_NOUNSET_APPLY\" in 1) set -u;; esac
unset MEZ_RESTORE_ERREXIT_APPLY MEZ_RESTORE_NOUNSET_APPLY
:
}}
__mez_agent_subshell_handoff; __mez_agent_subshell_cleanup; unset -f __mez_agent_subshell_handoff __mez_agent_subshell_cleanup 2>/dev/null || :; __mez_agent_subshell_restore_options; unset -f __mez_agent_subshell_restore_options 2>/dev/null || :
{direct_source_exit_boundary}\
",
            history_start = history_start,
            history_cleanup = history_cleanup,
            history_restore = history_restore,
            direct_source_exit_boundary = direct_source_exit_boundary,
            env_words = env_words,
            shell_invocation = shell_invocation,
        )
    };
    if classification == ShellClassification::Fish
        || (classification == ShellClassification::Bash && bash_receiver_rcfile.is_some())
    {
        Ok(source)
    } else {
        Ok(posix_shell_wrapper_transport(
            &source,
            classification,
            zsh_history_token,
        ))
    }
}
