//! Provider-independent local-action execution plans.
//!
//! This module owns the neutral plan emitted after a model-authored local
//! action is lowered. Product permission classification, pane-shell dispatch,
//! filesystem access, and execution remain in the Mezzanine composition
//! crate.

/// Identifies the semantic local action implementation selected before the
/// runtime chooses an execution transport.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LocalActionKind {
    /// A model-authored `shell_command` action.
    ShellCommand,
    /// A semantic `apply_patch` action lowered into local filesystem work.
    ApplyPatch,
}

/// Runtime-generated shell execution data for one local action.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalActionPlan {
    /// Semantic local action kind represented by this plan.
    pub kind: LocalActionKind,
    /// Concise user-facing summary shown before the action executes.
    pub summary: String,
    /// Exact pane shell input generated by the harness.
    pub command: String,
    /// Classifier-friendly command representing the same broad effect.
    pub policy_command: String,
    /// Whether the generated shell command expects direct user interaction.
    pub interactive: bool,
    /// Whether the generated shell command should run in the live pane shell.
    pub stateful: bool,
    /// Optional timeout for the generated shell command.
    pub timeout_ms: Option<u64>,
    /// Whether normal agent mode should show cleaned successful output even
    /// though raw shell output is otherwise hidden.
    pub display_output_after_completion: bool,
}

#[cfg(test)]
mod tests {
    use super::{LocalActionKind, LocalActionPlan};

    /// Local-action plans preserve the transport-neutral execution fields
    /// consumed by product permission and pane-shell adapters.
    #[test]
    fn local_action_plan_preserves_execution_contract() {
        let plan = LocalActionPlan {
            kind: LocalActionKind::ShellCommand,
            summary: "Inspect files".to_string(),
            command: "rg --files".to_string(),
            policy_command: "rg --files".to_string(),
            interactive: false,
            stateful: false,
            timeout_ms: Some(30_000),
            display_output_after_completion: false,
        };

        assert_eq!(plan.kind, LocalActionKind::ShellCommand);
        assert_eq!(plan.timeout_ms, Some(30_000));
        assert!(!plan.interactive);
    }
}
