//! Semantic MAAP action lowering.
//!
//! Models author MAAP actions such as `shell_command` and `apply_patch`. This
//! module owns deterministic conversion from those actions into runtime
//! execution plans. Local actions are expressed as pane shell transactions so
//! they operate inside the same local, remote, or container shell the user is
//! interacting with through Mezzanine.

use super::Result;
use super::maap::{
    AgentAction, AgentActionPayload, is_mez_patch_payload, validate_apply_patch_payload,
};
use super::shell::{shell_quote, validate_agent_authored_shell_command};
use base64::Engine;
use std::collections::{BTreeMap, BTreeSet};

/// Runtime-generated shell execution data for one local action.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalActionPlan {
    /// Concise user-facing summary shown before the action executes.
    pub summary: String,
    /// Exact pane shell input generated by Mezzanine.
    pub command: String,
    /// Classifier-friendly command representing the same broad effect.
    pub policy_command: String,
    /// Whether the generated shell command expects direct user interaction.
    pub interactive: bool,
    /// Whether the generated shell command should run in the live pane shell.
    pub stateful: bool,
    /// Optional timeout for the generated shell command.
    pub timeout_ms: Option<u64>,
    /// Whether normal agent mode should show the command's cleaned output after
    /// successful completion even though raw shell output is otherwise hidden.
    pub display_output_after_completion: bool,
}

/// Timeout for patch application actions.
///
/// Patch actions should either apply quickly or fail with a diagnostic that the
/// model can repair. Keeping them below the generic shell-action timeout avoids
/// making a malformed patch look like an indefinite stalled turn.
pub(super) const APPLY_PATCH_TIMEOUT_MS: u64 = 30 * 1000;
/// Marker that identifies the shell-backed read phase for `apply_patch`.
pub(super) const APPLY_PATCH_READ_PHASE_MARKER: &str = "__MEZ_APPLY_PATCH_READ_PHASE__";
/// Marker that identifies the shell-backed write phase for `apply_patch`.
pub(super) const APPLY_PATCH_WRITE_PHASE_MARKER: &str = "__MEZ_APPLY_PATCH_WRITE_PHASE__";
/// Marker that starts one `apply_patch` remote snapshot stream.
const APPLY_PATCH_READ_BEGIN_MARKER: &str = "__MEZ_APPLY_PATCH_READ_BEGIN__";
/// Marker that ends one `apply_patch` remote snapshot stream.
const APPLY_PATCH_READ_END_MARKER: &str = "__MEZ_APPLY_PATCH_READ_END__";
/// Marker that starts one path entry in an `apply_patch` snapshot stream.
const APPLY_PATCH_FILE_BEGIN_MARKER: &str = "__MEZ_APPLY_PATCH_FILE_BEGIN__";
/// Marker that ends one path entry in an `apply_patch` snapshot stream.
const APPLY_PATCH_FILE_END_MARKER: &str = "__MEZ_APPLY_PATCH_FILE_END__";
/// Marker that starts base64 file content in an `apply_patch` snapshot stream.
const APPLY_PATCH_CONTENT_BEGIN_MARKER: &str = "__MEZ_APPLY_PATCH_CONTENT_BEGIN__";
/// Marker that ends base64 file content in an `apply_patch` snapshot stream.
const APPLY_PATCH_CONTENT_END_MARKER: &str = "__MEZ_APPLY_PATCH_CONTENT_END__";
/// Maximum base64 payload bytes emitted on one generated shell-source line.
///
/// File mutations cross the pane PTY as shell input. Keeping individual lines
/// well below common canonical-line limits prevents large content writes from
/// filling the line discipline before the newline is accepted.
const FILE_CONTENT_BASE64_SHELL_LINE_BYTES: usize = 768;

/// One shell-backed phase used to complete an `apply_patch` action.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApplyPatchTransactionPhase {
    /// The action is reading remote file snapshots.
    Read,
    /// The action is verifying and writing patched bytes.
    Write,
}

/// Returns the local shell plan for a shell-backed MAAP action.
pub fn local_action_plan(action: &AgentAction) -> Result<Option<LocalActionPlan>> {
    match &action.payload {
        AgentActionPayload::ShellCommand {
            summary,
            command,
            interactive,
            stateful,
            timeout_ms: _,
        } => {
            validate_agent_authored_shell_command(command)?;
            Ok(Some(LocalActionPlan {
                summary: summary.clone(),
                command: command.clone(),
                policy_command: command.clone(),
                interactive: *interactive,
                stateful: *stateful,
                timeout_ms: None,
                display_output_after_completion: false,
            }))
        }
        AgentActionPayload::ApplyPatch { patch, strip } => {
            Ok(Some(apply_patch_plan(patch, *strip)?))
        }
        _ => Ok(None),
    }
}

/// Returns the user-facing summary for a shell-backed action.
pub fn local_action_summary(action: &AgentAction) -> Result<Option<String>> {
    Ok(local_action_plan(action)?.map(|plan| plan.summary))
}

/// Returns true when an action is implemented by a pane shell transaction.
pub fn action_is_local_shell_backed(action: &AgentAction) -> bool {
    matches!(
        action.payload,
        AgentActionPayload::ShellCommand { .. } | AgentActionPayload::ApplyPatch { .. }
    )
}

fn shell_print_line(line: &str) -> String {
    format!("printf '%s\\n' {}", shell_quote(line))
}

fn unified_diff_lines(
    title: &str,
    old_label: &str,
    new_label: &str,
    old_path: &str,
    new_path: &str,
) -> Vec<String> {
    vec![
        shell_print_line(&format!("diff -- {title}")),
        format!(
            "diff -u --label {old_label} --label {new_label} -- {old_path} {new_path}",
            old_label = shell_quote(old_label),
            new_label = shell_quote(new_label)
        ),
        "MEZ_DIFF_STATUS=$?".to_string(),
        "case \"$MEZ_DIFF_STATUS\" in 0|1) :;; *) exit \"$MEZ_DIFF_STATUS\";; esac".to_string(),
    ]
}

/// Builds shell lines that write exact content bytes without embedding the raw
/// payload in the generated shell source.
fn write_content_lines(content: &str, target: &str, append: bool) -> Vec<String> {
    let encoded = base64::engine::general_purpose::STANDARD.encode(content.as_bytes());
    let redirect = if append { ">>" } else { ">" };
    let mut lines = vec![
        "command -v base64 >/dev/null || { printf '%s\\n' 'base64 is required for semantic file content actions' >&2; exit 127; }"
            .to_string(),
        "MEZ_CONTENT_B64=$(mktemp) || exit 1".to_string(),
        "{".to_string(),
    ];
    if encoded.is_empty() {
        lines.push("  :".to_string());
    } else {
        for chunk in encoded
            .as_bytes()
            .chunks(FILE_CONTENT_BASE64_SHELL_LINE_BYTES)
        {
            let chunk = std::str::from_utf8(chunk)
                .expect("standard base64 output should always be valid UTF-8");
            lines.push(format!("  printf '%s' {}", shell_quote(chunk)));
        }
    }
    lines.extend([
        "} > \"$MEZ_CONTENT_B64\"".to_string(),
        format!(
            "if base64 -d < \"$MEZ_CONTENT_B64\" {redirect} {target} 2>/dev/null; then MEZ_CONTENT_STATUS=0; else base64 -D < \"$MEZ_CONTENT_B64\" {redirect} {target}; MEZ_CONTENT_STATUS=$?; fi"
        ),
        "rm -f -- \"$MEZ_CONTENT_B64\"".to_string(),
        "if [ \"$MEZ_CONTENT_STATUS\" != 0 ]; then exit \"$MEZ_CONTENT_STATUS\"; fi".to_string(),
    ]);
    lines
}

/// Returns the shell transaction phase represented by a generated apply-patch
/// command.
///
/// # Parameters
/// - `command`: The generated shell command being inspected.
pub fn apply_patch_transaction_phase(command: &str) -> Option<ApplyPatchTransactionPhase> {
    if command.contains(APPLY_PATCH_READ_PHASE_MARKER) {
        Some(ApplyPatchTransactionPhase::Read)
    } else if command.contains(APPLY_PATCH_WRITE_PHASE_MARKER) {
        Some(ApplyPatchTransactionPhase::Write)
    } else {
        None
    }
}

/// Builds the write phase for an `apply_patch` action from a remote snapshot.
///
/// # Parameters
/// - `patch`: The model-authored Mezzanine patch block.
/// - `read_output`: The decoded shell output from the read phase.
pub fn apply_patch_write_plan_from_read_output(
    patch: &str,
    read_output: &str,
) -> Result<LocalActionPlan> {
    let patch = parse_mez_patch(patch)?;
    let snapshots = parse_apply_patch_snapshot_output(read_output)?;
    let changes = apply_mez_patch_to_snapshots(&patch, &snapshots)?;
    mez_apply_patch_write_plan(changes)
}

/// Returns the sorted relative paths touched by one Mezzanine patch.
///
/// # Parameters
/// - `patch`: The model-authored Mezzanine patch block to inspect.
pub fn apply_patch_touched_paths(patch: &str) -> Result<Vec<String>> {
    Ok(parse_mez_patch(patch)?
        .touched_paths()
        .into_iter()
        .collect())
}

/// Builds a write-phase shell action that reports one deterministic
/// `apply_patch` error.
///
/// # Parameters
/// - `message`: The diagnostic to show to the model and user.
pub fn apply_patch_error_plan(message: &str) -> LocalActionPlan {
    let message = message.strip_prefix("apply_patch: ").unwrap_or(message);
    LocalActionPlan {
        summary: "I’ll apply a patch.".to_string(),
        command: format!(
            "# {APPLY_PATCH_WRITE_PHASE_MARKER}\nprintf '%s\\n' {} >&2\nexit 1",
            shell_quote(&format!("apply_patch: {message}"))
        ),
        policy_command: "apply_patch".to_string(),
        interactive: false,
        stateful: false,
        timeout_ms: Some(APPLY_PATCH_TIMEOUT_MS),
        display_output_after_completion: true,
    }
}

fn apply_patch_plan(patch: &str, strip: Option<u64>) -> Result<LocalActionPlan> {
    validate_apply_patch_payload(patch)?;
    debug_assert!(is_mez_patch_payload(patch));
    mez_apply_patch_read_plan(patch, strip)
}

fn mez_apply_patch_read_plan(patch: &str, strip: Option<u64>) -> Result<LocalActionPlan> {
    if strip.is_some() {
        return Err(super::MezError::invalid_args(
            "apply_patch strip is unsupported for Mezzanine patch blocks",
        ));
    }
    let patch = parse_mez_patch(patch)?;
    let command = mez_apply_patch_read_command(&patch.touched_paths());
    Ok(LocalActionPlan {
        summary: "I’ll apply a patch.".to_string(),
        command,
        policy_command: "apply_patch".to_string(),
        interactive: false,
        stateful: false,
        timeout_ms: Some(APPLY_PATCH_TIMEOUT_MS),
        display_output_after_completion: true,
    })
}

fn mez_apply_patch_write_plan(changes: Vec<ApplyPatchFileChange>) -> Result<LocalActionPlan> {
    let mut command = String::from("# ");
    command.push_str(APPLY_PATCH_WRITE_PHASE_MARKER);
    command.push('\n');
    command.push_str(&apply_patch_write_command_prelude());
    for (index, change) in changes.iter().enumerate() {
        command.push_str(&apply_patch_write_change_command(index, change));
    }
    Ok(LocalActionPlan {
        summary: "I’ll apply a patch.".to_string(),
        command,
        policy_command: "apply_patch".to_string(),
        interactive: false,
        stateful: false,
        timeout_ms: Some(APPLY_PATCH_TIMEOUT_MS),
        display_output_after_completion: true,
    })
}

fn mez_apply_patch_read_command(paths: &BTreeSet<String>) -> String {
    let mut lines = vec![
        format!("# {APPLY_PATCH_READ_PHASE_MARKER}"),
        "command -v base64 >/dev/null || { printf '%s\\n' 'apply_patch: base64 is required for apply_patch actions' >&2; exit 127; }".to_string(),
        "command -v realpath >/dev/null || { printf '%s\\n' 'apply_patch: coreutils realpath is required for apply_patch actions' >&2; exit 127; }".to_string(),
        "command -v tr >/dev/null || { printf '%s\\n' 'apply_patch: tr is required for apply_patch actions' >&2; exit 127; }".to_string(),
        "if ! realpath -m -- . >/dev/null 2>&1; then printf '%s\\n' 'apply_patch: coreutils realpath -m is required for apply_patch actions' >&2; exit 127; fi".to_string(),
        "MEZ_APPLY_CWD=$(pwd -P) || exit 1".to_string(),
        "MEZ_APPLY_CWD_PREFIX=${MEZ_APPLY_CWD%/}".to_string(),
        "if [ -z \"$MEZ_APPLY_CWD_PREFIX\" ]; then MEZ_APPLY_CWD_PREFIX=/; fi".to_string(),
        "mez_apply_patch_b64() { printf '%s' \"$1\" | base64 | tr -d '\\n'; }".to_string(),
        "mez_apply_patch_emit_path() {".to_string(),
        "MEZ_APPLY_PATH=$1".to_string(),
        "MEZ_APPLY_RESOLVED=$(realpath -m -- \"$MEZ_APPLY_PATH\" 2>/dev/null) || MEZ_APPLY_RESOLVED=".to_string(),
        "MEZ_APPLY_STATUS=error".to_string(),
        "if [ -n \"$MEZ_APPLY_RESOLVED\" ]; then".to_string(),
        "  case \"$MEZ_APPLY_RESOLVED\" in \"$MEZ_APPLY_CWD\"|\"$MEZ_APPLY_CWD_PREFIX\"/*)".to_string(),
        "    if [ -e \"$MEZ_APPLY_PATH\" ] || [ -L \"$MEZ_APPLY_PATH\" ]; then".to_string(),
        "      if [ -f \"$MEZ_APPLY_RESOLVED\" ]; then MEZ_APPLY_STATUS=regular; else MEZ_APPLY_STATUS=non_regular; fi".to_string(),
        "    else".to_string(),
        "      MEZ_APPLY_STATUS=missing".to_string(),
        "    fi".to_string(),
        "    ;;".to_string(),
        "  *) MEZ_APPLY_STATUS=outside_cwd ;;".to_string(),
        "  esac".to_string(),
        "fi".to_string(),
        format!("printf '%s\\n' {}", shell_quote(APPLY_PATCH_FILE_BEGIN_MARKER)),
        "printf 'PATH_B64 %s\\n' \"$(mez_apply_patch_b64 \"$MEZ_APPLY_PATH\")\"".to_string(),
        "printf 'RESOLVED_B64 %s\\n' \"$(mez_apply_patch_b64 \"$MEZ_APPLY_RESOLVED\")\"".to_string(),
        "printf 'STATUS %s\\n' \"$MEZ_APPLY_STATUS\"".to_string(),
        "if [ \"$MEZ_APPLY_STATUS\" = regular ]; then".to_string(),
        format!("  printf '%s\\n' {}", shell_quote(APPLY_PATCH_CONTENT_BEGIN_MARKER)),
        "  base64 < \"$MEZ_APPLY_RESOLVED\"".to_string(),
        format!("  printf '%s\\n' {}", shell_quote(APPLY_PATCH_CONTENT_END_MARKER)),
        "fi".to_string(),
        format!("printf '%s\\n' {}", shell_quote(APPLY_PATCH_FILE_END_MARKER)),
        "}".to_string(),
        format!("printf '%s\\n' {}", shell_quote(APPLY_PATCH_READ_BEGIN_MARKER)),
    ];
    for path in paths {
        lines.push(format!("mez_apply_patch_emit_path {}", shell_quote(path)));
    }
    lines.extend([
        format!("printf '%s\\n' {}", shell_quote(APPLY_PATCH_READ_END_MARKER)),
        "unset -f mez_apply_patch_emit_path mez_apply_patch_b64 2>/dev/null || :".to_string(),
        "unset MEZ_APPLY_CWD MEZ_APPLY_CWD_PREFIX MEZ_APPLY_PATH MEZ_APPLY_RESOLVED MEZ_APPLY_STATUS".to_string(),
    ]);
    lines.join("\n")
}

fn apply_patch_write_command_prelude() -> String {
    [
        "command -v base64 >/dev/null || { printf '%s\\n' 'apply_patch: base64 is required for apply_patch actions' >&2; exit 127; }",
        "command -v realpath >/dev/null || { printf '%s\\n' 'apply_patch: coreutils realpath is required for apply_patch actions' >&2; exit 127; }",
        "command -v cmp >/dev/null || { printf '%s\\n' 'apply_patch: cmp is required for apply_patch actions' >&2; exit 127; }",
        "command -v dirname >/dev/null || { printf '%s\\n' 'apply_patch: dirname is required for apply_patch actions' >&2; exit 127; }",
        "if ! realpath -m -- . >/dev/null 2>&1; then printf '%s\\n' 'apply_patch: coreutils realpath -m is required for apply_patch actions' >&2; exit 127; fi",
        "MEZ_APPLY_CWD=$(pwd -P) || exit 1",
        "MEZ_APPLY_CWD_PREFIX=${MEZ_APPLY_CWD%/}",
        "if [ -z \"$MEZ_APPLY_CWD_PREFIX\" ]; then MEZ_APPLY_CWD_PREFIX=/; fi",
        "mez_apply_patch_resolve_checked() {",
        "MEZ_APPLY_PATH=$1",
        "MEZ_APPLY_EXPECTED_RESOLVED=$2",
        "MEZ_APPLY_RESOLVED=$(realpath -m -- \"$MEZ_APPLY_PATH\" 2>/dev/null) || { printf '%s\\n' \"apply_patch: failed to resolve path: $MEZ_APPLY_PATH\" >&2; exit 1; }",
        "case \"$MEZ_APPLY_RESOLVED\" in \"$MEZ_APPLY_CWD\"|\"$MEZ_APPLY_CWD_PREFIX\"/*) ;; *) printf '%s\\n' \"apply_patch: resolved path is outside current working directory: $MEZ_APPLY_PATH\" >&2; exit 1;; esac",
        "if [ \"$MEZ_APPLY_RESOLVED\" != \"$MEZ_APPLY_EXPECTED_RESOLVED\" ]; then printf '%s\\n' \"apply_patch: resolved path changed before apply: $MEZ_APPLY_PATH\" >&2; exit 1; fi",
        "}",
        "",
    ]
    .join("\n")
}

fn apply_patch_write_change_command(index: usize, change: &ApplyPatchFileChange) -> String {
    let expected_var = format!("MEZ_APPLY_EXPECTED_{index}");
    let new_var = format!("MEZ_APPLY_NEW_{index}");
    let original_is_regular = matches!(&change.original, ApplyPatchOriginalState::Regular(_));
    let mut lines = vec![format!(
        "mez_apply_patch_resolve_checked {} {}",
        shell_quote(&change.path),
        shell_quote(&change.resolved_path)
    )];
    match &change.original {
        ApplyPatchOriginalState::Regular(bytes) => {
            lines.push(format!("{expected_var}=$(mktemp) || exit 1"));
            lines.extend(write_content_lines(
                &String::from_utf8_lossy(bytes),
                &format!("\"${expected_var}\""),
                false,
            ));
            lines.push(format!(
                "if [ ! -f \"$MEZ_APPLY_RESOLVED\" ]; then printf '%s\\n' {} >&2; rm -f -- \"${expected_var}\"; exit 1; fi",
                shell_quote(&format!(
                    "apply_patch: refusing to patch non-regular file: {}",
                    change.path
                ))
            ));
            lines.push(format!(
                "if ! cmp -s -- \"${expected_var}\" \"$MEZ_APPLY_RESOLVED\"; then printf '%s\\n' {} >&2; rm -f -- \"${expected_var}\"; exit 1; fi",
                shell_quote(&format!("apply_patch: file changed before apply: {}", change.path))
            ));
        }
        ApplyPatchOriginalState::Missing => {
            lines.push(format!(
                "if [ -e {} ] || [ -L {} ] || [ -e \"$MEZ_APPLY_RESOLVED\" ] || [ -L \"$MEZ_APPLY_RESOLVED\" ]; then printf '%s\\n' {} >&2; exit 1; fi",
                shell_quote(&change.path),
                shell_quote(&change.path),
                shell_quote(&format!("apply_patch: refusing to add existing path: {}", change.path))
            ));
        }
    }
    if let Some(bytes) = &change.final_bytes {
        lines.push(format!("{new_var}=$(mktemp) || exit 1"));
        lines.extend(write_content_lines(
            &String::from_utf8_lossy(bytes),
            &format!("\"${new_var}\""),
            false,
        ));
        let old_label = if original_is_regular {
            format!("a/{}", change.path)
        } else {
            "/dev/null".to_string()
        };
        let old_path = if original_is_regular {
            format!("\"${expected_var}\"")
        } else {
            shell_quote("/dev/null")
        };
        lines.extend(unified_diff_lines(
            "apply patch",
            &old_label,
            &format!("b/{}", change.path),
            &old_path,
            &format!("\"${new_var}\""),
        ));
        lines.push("mkdir -p -- \"$(dirname -- \"$MEZ_APPLY_RESOLVED\")\"".to_string());
        lines.push(format!("mv -f -- \"${new_var}\" \"$MEZ_APPLY_RESOLVED\""));
    } else {
        lines.extend(unified_diff_lines(
            "apply patch",
            &format!("a/{}", change.path),
            "/dev/null",
            &format!("\"${expected_var}\""),
            &shell_quote("/dev/null"),
        ));
        lines.push("rm -f -- \"$MEZ_APPLY_RESOLVED\"".to_string());
    }
    if original_is_regular {
        lines.push(format!("rm -f -- \"${expected_var}\""));
    }
    lines.join("\n") + "\n"
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct MezPatch {
    operations: Vec<MezPatchOperation>,
}

impl MezPatch {
    fn touched_paths(&self) -> BTreeSet<String> {
        let mut paths = BTreeSet::new();
        for operation in &self.operations {
            match operation {
                MezPatchOperation::Add { path, .. }
                | MezPatchOperation::Delete { path }
                | MezPatchOperation::Update { path, .. } => {
                    paths.insert(path.clone());
                }
            }
            if let MezPatchOperation::Update {
                move_to: Some(move_to),
                ..
            } = operation
            {
                paths.insert(move_to.clone());
            }
        }
        paths
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum MezPatchOperation {
    Add {
        path: String,
        content: Vec<String>,
    },
    Delete {
        path: String,
    },
    Update {
        path: String,
        move_to: Option<String>,
        hunks: Vec<MezPatchHunk>,
        trailing_newline: Option<bool>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct MezPatchHunk {
    anchors: Vec<String>,
    range_hint: Option<MezPatchRangeHint>,
    lines: Vec<MezPatchHunkLine>,
    old: Vec<String>,
    new: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct MezPatchRangeHint {
    old_start: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum MezPatchHunkLine {
    Context(String),
    Remove(String),
    Add(String),
}

impl MezPatchHunk {
    fn replacement_lines(
        &self,
        file: &ApplyPatchTextFile,
        hunk_match: &ApplyPatchHunkMatch,
    ) -> Result<Vec<String>> {
        let mut old_index = 0usize;
        let mut next_source_offset = 0usize;
        let mut lines = Vec::new();
        let gap_policies = self.old_line_gap_policies();
        for line in &self.lines {
            match line {
                MezPatchHunkLine::Context(_) => {
                    let gap_policy = *gap_policies
                        .get(old_index)
                        .unwrap_or(&ApplyPatchBlankGapPolicy::Disallow);
                    let offset = *hunk_match.old_line_offsets.get(old_index).ok_or_else(|| {
                        super::MezError::invalid_args(
                            "apply_patch: internal hunk replacement range was invalid",
                        )
                    })?;
                    append_skipped_blank_context_lines(
                        &mut lines,
                        file,
                        hunk_match.position,
                        next_source_offset,
                        offset,
                        gap_policy,
                    )?;
                    let source = file
                        .lines
                        .get(hunk_match.position + offset)
                        .ok_or_else(|| {
                            super::MezError::invalid_args(
                                "apply_patch: internal hunk replacement range was invalid",
                            )
                        })?;
                    lines.push(source.clone());
                    old_index += 1;
                    next_source_offset = offset.saturating_add(1);
                }
                MezPatchHunkLine::Remove(_) => {
                    let gap_policy = *gap_policies
                        .get(old_index)
                        .unwrap_or(&ApplyPatchBlankGapPolicy::Disallow);
                    let offset = *hunk_match.old_line_offsets.get(old_index).ok_or_else(|| {
                        super::MezError::invalid_args(
                            "apply_patch: internal hunk replacement range was invalid",
                        )
                    })?;
                    append_skipped_blank_context_lines(
                        &mut lines,
                        file,
                        hunk_match.position,
                        next_source_offset,
                        offset,
                        gap_policy,
                    )?;
                    next_source_offset = offset.saturating_add(1);
                    old_index += 1;
                }
                MezPatchHunkLine::Add(text) => lines.push(text.clone()),
            }
        }
        Ok(lines)
    }

    fn old_line_gap_policies(&self) -> Vec<ApplyPatchBlankGapPolicy> {
        let mut policies = Vec::with_capacity(self.old.len());
        let mut previous_old_kind = None;
        for line in &self.lines {
            match line {
                MezPatchHunkLine::Context(_) => {
                    let policy = match previous_old_kind {
                        Some(MezPatchOldLineKind::Context | MezPatchOldLineKind::Remove) => {
                            ApplyPatchBlankGapPolicy::Preserve
                        }
                        _ => ApplyPatchBlankGapPolicy::Disallow,
                    };
                    policies.push(policy);
                    previous_old_kind = Some(MezPatchOldLineKind::Context);
                }
                MezPatchHunkLine::Remove(_) => {
                    let policy = match previous_old_kind {
                        Some(MezPatchOldLineKind::Context | MezPatchOldLineKind::Remove) => {
                            ApplyPatchBlankGapPolicy::Delete
                        }
                        _ => ApplyPatchBlankGapPolicy::Disallow,
                    };
                    policies.push(policy);
                    previous_old_kind = Some(MezPatchOldLineKind::Remove);
                }
                MezPatchHunkLine::Add(_) => {}
            }
        }
        policies
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum MezPatchOldLineKind {
    Context,
    Remove,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ApplyPatchBlankGapPolicy {
    Disallow,
    Preserve,
    Delete,
}

fn append_skipped_blank_context_lines(
    output: &mut Vec<String>,
    file: &ApplyPatchTextFile,
    position: usize,
    start_offset: usize,
    end_offset: usize,
    policy: ApplyPatchBlankGapPolicy,
) -> Result<()> {
    if end_offset <= start_offset {
        return Ok(());
    }
    if policy == ApplyPatchBlankGapPolicy::Disallow {
        return Err(super::MezError::invalid_args(
            "apply_patch: internal hunk replacement range was invalid",
        ));
    }
    for offset in start_offset..end_offset {
        let source = file.lines.get(position + offset).ok_or_else(|| {
            super::MezError::invalid_args(
                "apply_patch: internal hunk replacement range was invalid",
            )
        })?;
        if !source.trim().is_empty() {
            return Err(super::MezError::invalid_args(
                "apply_patch: internal hunk replacement range was invalid",
            ));
        }
        if policy == ApplyPatchBlankGapPolicy::Preserve {
            output.push(source.clone());
        }
    }
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ApplyPatchSnapshot {
    path: String,
    resolved_path: String,
    state: ApplyPatchSnapshotState,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum ApplyPatchSnapshotState {
    Regular(Vec<u8>),
    Missing,
    NonRegular,
    OutsideCwd,
    Error,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ApplyPatchFileChange {
    path: String,
    resolved_path: String,
    original: ApplyPatchOriginalState,
    final_bytes: Option<Vec<u8>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum ApplyPatchOriginalState {
    Regular(Vec<u8>),
    Missing,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ApplyPatchTextFile {
    lines: Vec<String>,
    trailing_newline: bool,
}

impl ApplyPatchTextFile {
    fn from_bytes(path: &str, bytes: &[u8]) -> Result<Self> {
        let text = String::from_utf8(bytes.to_vec()).map_err(|_| {
            super::MezError::invalid_args(format!("apply_patch: file is not valid UTF-8: {path}"))
        })?;
        Ok(Self {
            lines: text.lines().map(ToString::to_string).collect(),
            trailing_newline: text.ends_with('\n'),
        })
    }

    fn from_lines(lines: Vec<String>, trailing_newline: bool) -> Self {
        Self {
            lines,
            trailing_newline,
        }
    }

    fn into_bytes(self) -> Vec<u8> {
        let mut text = self.lines.join("\n");
        if !self.lines.is_empty() && self.trailing_newline {
            text.push('\n');
        }
        text.into_bytes()
    }
}

fn parse_mez_patch(text: &str) -> Result<MezPatch> {
    let text = normalize_mez_patch_text(text);
    let lines = text.lines().collect::<Vec<_>>();
    let mut index = 0usize;
    while index < lines.len() && lines[index].trim().is_empty() {
        index += 1;
    }
    if lines.get(index).map(|line| line.trim()) != Some("*** Begin Patch") {
        return apply_patch_parse_error("Mezzanine patch must start with *** Begin Patch");
    }
    index += 1;
    let mut operations = Vec::new();
    while index < lines.len() {
        let line = lines[index].trim();
        if line == "*** End Patch" {
            index += 1;
            break;
        }
        if let Some(path) = line.strip_prefix("*** Add File: ") {
            let path = clean_mez_patch_path(path)?;
            index += 1;
            let mut content = Vec::new();
            while index < lines.len() && !is_mez_patch_directive_line(lines[index]) {
                let Some(line) = lines[index].strip_prefix('+') else {
                    return apply_patch_parse_error("add-file lines must start with +");
                };
                content.push(line.to_string());
                index += 1;
            }
            operations.push(MezPatchOperation::Add { path, content });
            continue;
        }
        if let Some(path) = line.strip_prefix("*** Delete File: ") {
            operations.push(MezPatchOperation::Delete {
                path: clean_mez_patch_path(path)?,
            });
            index += 1;
            continue;
        }
        if let Some(path) = line.strip_prefix("*** Update File: ") {
            let path = clean_mez_patch_path(path)?;
            index += 1;
            let mut move_to = None;
            if let Some(target) = lines
                .get(index)
                .map(|line| line.trim())
                .and_then(|line| line.strip_prefix("*** Move to: "))
            {
                move_to = Some(clean_mez_patch_path(target)?);
                index += 1;
            }
            let mut hunks = Vec::new();
            let mut trailing_newline = None;
            while index < lines.len() && !is_mez_patch_directive_line(lines[index]) {
                if lines[index].trim().is_empty() {
                    index += 1;
                    continue;
                }
                let (next_index, hunk, hunk_trailing_newline) =
                    parse_mez_patch_hunk(&lines, index, hunks.is_empty())?;
                if let Some(value) = hunk_trailing_newline {
                    trailing_newline = Some(value);
                }
                hunks.push(hunk);
                index = next_index;
            }
            if hunks.is_empty() {
                return apply_patch_parse_error(&format!(
                    "update-file operation for path {path} must contain at least one hunk"
                ));
            }
            operations.push(MezPatchOperation::Update {
                path,
                move_to,
                hunks,
                trailing_newline,
            });
            continue;
        }
        return apply_patch_parse_error(&format!("unsupported patch directive: {line}"));
    }
    if lines.get(index.saturating_sub(1)).map(|line| line.trim()) != Some("*** End Patch") {
        return apply_patch_parse_error("Mezzanine patch must end with *** End Patch");
    }
    if lines[index..].iter().any(|line| !line.trim().is_empty()) {
        return apply_patch_parse_error("unexpected content after *** End Patch");
    }
    Ok(MezPatch { operations })
}

fn normalize_mez_patch_text(text: &str) -> std::borrow::Cow<'_, str> {
    let trimmed = text.trim();
    if let Some(fenced) = mez_patch_fenced_body(trimmed) {
        if let Some(heredoc) = mez_patch_heredoc_body(&fenced) {
            return std::borrow::Cow::Owned(dedent_mez_patch_text(&heredoc).into_owned());
        }
        return std::borrow::Cow::Owned(dedent_mez_patch_text(&fenced).into_owned());
    }
    if let Some(heredoc) = mez_patch_heredoc_body(trimmed) {
        return std::borrow::Cow::Owned(dedent_mez_patch_text(&heredoc).into_owned());
    }
    dedent_mez_patch_text(text)
}

fn dedent_mez_patch_text(text: &str) -> std::borrow::Cow<'_, str> {
    let Some(first_nonblank) = text.lines().find(|line| !line.trim().is_empty()) else {
        return std::borrow::Cow::Borrowed(text);
    };
    let trimmed_first = first_nonblank.trim_start();
    if trimmed_first != "*** Begin Patch" || trimmed_first == first_nonblank {
        return std::borrow::Cow::Borrowed(text);
    }
    let indent = &first_nonblank[..first_nonblank.len() - trimmed_first.len()];
    let mut dedented = String::with_capacity(text.len());
    for (index, line) in text.lines().enumerate() {
        if index > 0 {
            dedented.push('\n');
        }
        if let Some(stripped) = line.strip_prefix(indent) {
            dedented.push_str(stripped);
        } else {
            dedented.push_str(line);
        }
    }
    if text.ends_with('\n') {
        dedented.push('\n');
    }
    std::borrow::Cow::Owned(dedented)
}

fn mez_patch_fenced_body(trimmed: &str) -> Option<String> {
    let newline = trimmed.find('\n')?;
    let first_line = trimmed[..newline].trim();
    if !first_line.starts_with("```") {
        return None;
    }
    let body = &trimmed[newline + 1..];
    let mut body_lines = body.lines().collect::<Vec<_>>();
    if body_lines.last().is_some_and(|line| line.trim() == "```") {
        body_lines.pop();
        return Some(trim_mez_patch_wrapper_body(&body_lines));
    }
    None
}

fn mez_patch_heredoc_body(trimmed: &str) -> Option<String> {
    let newline = trimmed.find('\n')?;
    let first_line = trimmed[..newline].trim();
    let delimiter = mez_patch_heredoc_delimiter(first_line)?;
    let body = &trimmed[newline + 1..];
    let mut body_lines = body.lines().collect::<Vec<_>>();
    if body_lines
        .last()
        .is_some_and(|line| line.trim() == delimiter)
    {
        body_lines.pop();
        return Some(trim_mez_patch_wrapper_body(&body_lines));
    }
    None
}

fn trim_mez_patch_wrapper_body(lines: &[&str]) -> String {
    let mut start = 0usize;
    let mut end = lines.len();
    while start < end && lines[start].trim().is_empty() {
        start += 1;
    }
    while end > start && lines[end - 1].trim().is_empty() {
        end -= 1;
    }
    lines[start..end].join("\n")
}

fn mez_patch_heredoc_delimiter(line: &str) -> Option<&str> {
    let line = line.trim();
    let redirect = if let Some(redirect) = line.strip_prefix("<<") {
        redirect
    } else {
        line.strip_prefix("apply_patch")?
            .trim_start()
            .strip_prefix("<<")?
    };
    let delimiter = redirect.strip_prefix('-').unwrap_or(redirect).trim();
    let delimiter = delimiter
        .strip_prefix('\'')
        .and_then(|delimiter| delimiter.strip_suffix('\''))
        .or_else(|| {
            delimiter
                .strip_prefix('"')
                .and_then(|delimiter| delimiter.strip_suffix('"'))
        })
        .unwrap_or(delimiter);
    (!delimiter.is_empty()
        && delimiter
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || character == '_'))
    .then_some(delimiter)
}

fn is_mez_patch_directive_line(line: &str) -> bool {
    matches!(line.trim(), "*** End Patch" | "*** End of File")
        || line.trim().starts_with("*** Add File: ")
        || line.trim().starts_with("*** Delete File: ")
        || line.trim().starts_with("*** Update File: ")
        || line.trim().starts_with("*** Move to: ")
}

fn parse_mez_patch_hunk(
    lines: &[&str],
    mut index: usize,
    allow_missing_header: bool,
) -> Result<(usize, MezPatchHunk, Option<bool>)> {
    if index >= lines.len() {
        return apply_patch_parse_error("expected hunk header");
    }
    let (anchors, range_hint) = if is_mez_hunk_header_line(lines[index]) {
        let (anchors, range_hint) = parse_mez_patch_hunk_header(lines[index].trim());
        index += 1;
        (anchors, range_hint)
    } else if allow_missing_header {
        (Vec::new(), None)
    } else {
        return apply_patch_parse_error("expected hunk header");
    };
    let mut hunk_lines = Vec::new();
    let mut old = Vec::new();
    let mut new = Vec::new();
    let mut trailing_newline = None;
    while index < lines.len() {
        let line = lines[index];
        if is_mez_hunk_header_line(line)
            || (is_mez_patch_directive_line(line) && line.trim() != "*** End of File")
        {
            break;
        }
        if line.trim() == "*** End of File" {
            trailing_newline = Some(false);
            index += 1;
            continue;
        }
        let Some(prefix) = line.chars().next() else {
            old.push(String::new());
            new.push(String::new());
            hunk_lines.push(MezPatchHunkLine::Context(String::new()));
            index += 1;
            continue;
        };
        let content = &line[prefix.len_utf8()..];
        match prefix {
            ' ' => {
                old.push(content.to_string());
                new.push(content.to_string());
                hunk_lines.push(MezPatchHunkLine::Context(content.to_string()));
            }
            '-' => {
                old.push(content.to_string());
                hunk_lines.push(MezPatchHunkLine::Remove(content.to_string()));
            }
            '+' => {
                new.push(content.to_string());
                hunk_lines.push(MezPatchHunkLine::Add(content.to_string()));
            }
            _ => return apply_patch_parse_error("patch hunk lines must start with space, +, or -"),
        }
        index += 1;
    }
    if hunk_lines.is_empty() {
        return apply_patch_parse_error("update hunk does not contain any lines");
    }
    Ok((
        index,
        MezPatchHunk {
            anchors,
            range_hint,
            lines: hunk_lines,
            old,
            new,
        },
        trailing_newline,
    ))
}

fn is_mez_hunk_header_line(line: &str) -> bool {
    line.starts_with("@@")
        || (!line.starts_with([' ', '+', '-']) && line.trim_start().starts_with("@@"))
}

fn parse_mez_patch_hunk_header(header: &str) -> (Vec<String>, Option<MezPatchRangeHint>) {
    let body = header.strip_prefix("@@").unwrap_or(header).trim();
    let (body, range_hint) = strip_unified_hunk_range_metadata(body);
    let anchors = body
        .split("@@")
        .map(str::trim)
        .filter(|anchor| !anchor.is_empty())
        .map(ToString::to_string)
        .collect();
    (anchors, range_hint)
}

fn strip_unified_hunk_range_metadata(body: &str) -> (&str, Option<MezPatchRangeHint>) {
    let Some(after_old_prefix) = body.strip_prefix('-') else {
        return (body, None);
    };
    let Some((old_start, after_old_range)) = consume_unified_hunk_range(after_old_prefix) else {
        return (body, None);
    };
    let Some(after_new_prefix) = after_old_range.trim_start().strip_prefix('+') else {
        return (body, None);
    };
    let Some((_, after_new_range)) = consume_unified_hunk_range(after_new_prefix) else {
        return (body, None);
    };
    let after_ranges = after_new_range.trim_start();
    let Some(after_closing_marker) = after_ranges.strip_prefix("@@") else {
        return (body, None);
    };
    (
        after_closing_marker.trim_start(),
        Some(MezPatchRangeHint { old_start }),
    )
}

fn consume_unified_hunk_range(text: &str) -> Option<(usize, &str)> {
    let (start, text) = consume_ascii_number(text)?;
    let text = if let Some(after_comma) = text.strip_prefix(',') {
        consume_ascii_number(after_comma)?.1
    } else {
        text
    };
    if text.is_empty()
        || text
            .chars()
            .next()
            .is_some_and(|character| character.is_ascii_whitespace() || character == '@')
    {
        Some((start, text))
    } else {
        None
    }
}

fn consume_ascii_number(text: &str) -> Option<(usize, &str)> {
    let mut end = 0usize;
    for (index, character) in text.char_indices() {
        if !character.is_ascii_digit() {
            break;
        }
        end = index + character.len_utf8();
    }
    if end == 0 {
        return None;
    }
    Some((text[..end].parse().ok()?, &text[end..]))
}

fn clean_mez_patch_path(raw: &str) -> Result<String> {
    let mut raw = raw.trim();
    raw = raw
        .strip_prefix("a/")
        .or_else(|| raw.strip_prefix("b/"))
        .unwrap_or(raw);
    while let Some(stripped) = raw.strip_prefix("./") {
        raw = stripped;
    }
    if raw.is_empty() || raw.starts_with('/') {
        return apply_patch_parse_error(&format!("unsafe patch path: {raw}"));
    }
    let mut parts = Vec::new();
    for part in raw.split('/') {
        match part {
            "" | ".." => return apply_patch_parse_error(&format!("unsafe patch path: {raw}")),
            "." => {}
            _ => parts.push(part),
        }
    }
    if parts.is_empty() {
        return apply_patch_parse_error(&format!("unsafe patch path: {raw}"));
    }
    Ok(parts.join("/"))
}

fn apply_patch_parse_error<T>(message: &str) -> Result<T> {
    Err(super::MezError::invalid_args(format!(
        "apply_patch: {message}"
    )))
}

fn parse_apply_patch_snapshot_output(output: &str) -> Result<BTreeMap<String, ApplyPatchSnapshot>> {
    let mut lines = output.replace("\r\n", "\n").replace('\r', "\n");
    if !lines.ends_with('\n') {
        lines.push('\n');
    }
    let lines = lines.lines().collect::<Vec<_>>();
    let begin = lines
        .iter()
        .position(|line| *line == APPLY_PATCH_READ_BEGIN_MARKER)
        .ok_or_else(|| {
            super::MezError::invalid_args(
                "apply_patch: read phase did not emit a snapshot begin marker",
            )
        })?;
    let end = lines
        .iter()
        .rposition(|line| *line == APPLY_PATCH_READ_END_MARKER)
        .ok_or_else(|| {
            super::MezError::invalid_args(
                "apply_patch: read phase did not emit a snapshot end marker",
            )
        })?;
    let mut index = begin + 1;
    let mut snapshots = BTreeMap::new();
    while index < end {
        if lines[index] != APPLY_PATCH_FILE_BEGIN_MARKER {
            return apply_patch_parse_error("malformed remote snapshot entry");
        }
        index += 1;
        let path = decode_apply_patch_snapshot_field(lines.get(index), "PATH_B64")?;
        index += 1;
        let resolved_path = decode_apply_patch_snapshot_field(lines.get(index), "RESOLVED_B64")?;
        index += 1;
        let status = lines
            .get(index)
            .and_then(|line| line.strip_prefix("STATUS "))
            .ok_or_else(|| {
                super::MezError::invalid_args("apply_patch: malformed remote snapshot status")
            })?;
        index += 1;
        let state = match status {
            "regular" => {
                if lines.get(index) != Some(&APPLY_PATCH_CONTENT_BEGIN_MARKER) {
                    return apply_patch_parse_error("regular remote snapshot omitted content");
                }
                index += 1;
                let mut encoded = String::new();
                while index < end && lines[index] != APPLY_PATCH_CONTENT_END_MARKER {
                    encoded.push_str(lines[index].trim());
                    index += 1;
                }
                if lines.get(index) != Some(&APPLY_PATCH_CONTENT_END_MARKER) {
                    return apply_patch_parse_error(
                        "regular remote snapshot content was unterminated",
                    );
                }
                index += 1;
                ApplyPatchSnapshotState::Regular(decode_base64_bytes(&encoded, "file content")?)
            }
            "missing" => ApplyPatchSnapshotState::Missing,
            "non_regular" => ApplyPatchSnapshotState::NonRegular,
            "outside_cwd" => ApplyPatchSnapshotState::OutsideCwd,
            _ => ApplyPatchSnapshotState::Error,
        };
        if lines.get(index) != Some(&APPLY_PATCH_FILE_END_MARKER) {
            return apply_patch_parse_error("remote snapshot entry was unterminated");
        }
        index += 1;
        snapshots.insert(
            path.clone(),
            ApplyPatchSnapshot {
                path,
                resolved_path,
                state,
            },
        );
    }
    Ok(snapshots)
}

fn decode_apply_patch_snapshot_field(line: Option<&&str>, name: &str) -> Result<String> {
    let encoded = line
        .and_then(|line| line.strip_prefix(&format!("{name} ")))
        .ok_or_else(|| {
            super::MezError::invalid_args(format!("apply_patch: missing snapshot field {name}"))
        })?;
    let bytes = decode_base64_bytes(encoded, name)?;
    String::from_utf8(bytes).map_err(|_| {
        super::MezError::invalid_args(format!("apply_patch: snapshot field {name} is not UTF-8"))
    })
}

fn decode_base64_bytes(encoded: &str, label: &str) -> Result<Vec<u8>> {
    base64::engine::general_purpose::STANDARD
        .decode(encoded.as_bytes())
        .map_err(|error| {
            super::MezError::invalid_args(format!(
                "apply_patch: failed to decode {label} base64: {error}"
            ))
        })
}

fn apply_mez_patch_to_snapshots(
    patch: &MezPatch,
    snapshots: &BTreeMap<String, ApplyPatchSnapshot>,
) -> Result<Vec<ApplyPatchFileChange>> {
    let mut current = BTreeMap::new();
    let mut original = BTreeMap::new();
    for (path, snapshot) in snapshots {
        let state = snapshot_text_state(snapshot)?;
        original.insert(path.clone(), state.clone());
        current.insert(path.clone(), state);
    }
    for operation in &patch.operations {
        match operation {
            MezPatchOperation::Add { path, content } => {
                ensure_missing_state(path, current.get(path))?;
                current.insert(
                    path.clone(),
                    Some(ApplyPatchTextFile::from_lines(content.clone(), true)),
                );
            }
            MezPatchOperation::Delete { path } => {
                ensure_regular_state(path, current.get(path))?;
                current.insert(path.clone(), None);
            }
            MezPatchOperation::Update {
                path,
                move_to,
                hunks,
                trailing_newline,
            } => {
                let mut file = ensure_regular_state(path, current.get(path))?.clone();
                if let Some(value) = trailing_newline {
                    file.trailing_newline = *value;
                }
                let mut cursor = 0usize;
                for hunk in hunks {
                    let hunk_match =
                        find_hunk_position(&file, hunk, cursor).map_err(|problem| {
                            apply_patch_hunk_mismatch_error(path, &file, hunk, problem)
                        })?;
                    let replacement = hunk.replacement_lines(&file, &hunk_match)?;
                    let replacement_len = replacement.len();
                    file.lines.splice(
                        hunk_match.position..hunk_match.position + hunk_match.span_len(),
                        replacement,
                    );
                    cursor = hunk_match.position + replacement_len;
                }
                if let Some(target) = move_to {
                    ensure_missing_state(target, current.get(target))?;
                    current.insert(path.clone(), None);
                    current.insert(target.clone(), Some(file));
                } else {
                    current.insert(path.clone(), Some(file));
                }
            }
        }
    }
    let mut changes = Vec::new();
    for path in patch.touched_paths() {
        let snapshot = snapshots.get(&path).ok_or_else(|| {
            super::MezError::invalid_args(format!(
                "apply_patch: missing remote snapshot for path: {path}"
            ))
        })?;
        let original_state = match original.get(&path).cloned().flatten() {
            Some(file) => ApplyPatchOriginalState::Regular(file.into_bytes()),
            None => ApplyPatchOriginalState::Missing,
        };
        let final_bytes = current
            .get(&path)
            .cloned()
            .flatten()
            .map(|file| file.into_bytes());
        let original_empty = matches!(original_state, ApplyPatchOriginalState::Missing);
        if original_empty && final_bytes.is_none() {
            continue;
        }
        changes.push(ApplyPatchFileChange {
            path,
            resolved_path: snapshot.resolved_path.clone(),
            original: original_state,
            final_bytes,
        });
    }
    Ok(changes)
}

fn apply_patch_hunk_mismatch_error(
    path: &str,
    file: &ApplyPatchTextFile,
    hunk: &MezPatchHunk,
    problem: ApplyPatchHunkMatchProblem,
) -> super::MezError {
    let (failure_code, reason, candidate_lines, context_center, missing_anchor, mode, attempts) =
        match problem {
            ApplyPatchHunkMatchProblem::Missing {
                context_center,
                missing_anchor,
                attempts,
            } => (
                "HUNK_CONTEXT_MISMATCH",
                "hunk context was not found in the current file",
                Vec::new(),
                context_center,
                missing_anchor,
                None,
                attempts,
            ),
            ApplyPatchHunkMatchProblem::Ambiguous {
                candidate_lines,
                mode,
                attempts,
            } => {
                let reason = match mode {
                    Some(ApplyPatchMatchMode::Exact) | None => {
                        "exact hunk context is ambiguous in the current file"
                    }
                    Some(ApplyPatchMatchMode::TrimEnd) => {
                        "trim_end hunk context is ambiguous in the current file"
                    }
                    Some(ApplyPatchMatchMode::Trim) => {
                        "trim hunk context is ambiguous in the current file"
                    }
                    Some(ApplyPatchMatchMode::Normalized) => {
                        "normalized hunk context is ambiguous in the current file"
                    }
                };
                (
                    "HUNK_CONTEXT_AMBIGUOUS",
                    reason,
                    candidate_lines,
                    None,
                    None,
                    mode,
                    attempts,
                )
            }
        };
    let mut message = format!(
        "apply_patch: hunk did not match: {path}\n\
         apply_patch: {reason}\n\
         apply_patch: failure_code={failure_code}\n\
         apply_patch: affected_path={path}\n\
         apply_patch: failed old-context line count: {}",
        hunk.old.len()
    );
    if !attempts.is_empty() {
        message.push_str(&format!(
            "\napply_patch: matching_attempts={}",
            apply_patch_match_attempts_summary(&attempts)
        ));
    }
    if let Some(mode) = mode {
        message.push_str(&format!(
            "\napply_patch: ambiguous_matching_mode={}",
            mode.as_str()
        ));
    }
    if !hunk.anchors.is_empty() {
        message.push_str(&format!(
            "\napply_patch: hunk header anchor(s): {}",
            hunk.anchors.join(" -> ")
        ));
    }
    if let Some(range_hint) = hunk.range_hint {
        message.push_str(&format!(
            "\napply_patch: hunk header old-line hint: {}",
            range_hint.old_start
        ));
    }
    if let Some(anchor) = missing_anchor {
        message.push_str(&format!(
            "\napply_patch: hunk header anchor was not found in order: {}",
            apply_patch_mismatch_excerpt(&anchor)
        ));
    }
    if !candidate_lines.is_empty() {
        message.push_str(&format!(
            "\napply_patch: candidate match line(s): {}",
            candidate_lines
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    if let Some(first_line) = hunk.old.first() {
        let anchor_lines = apply_patch_anchor_line_numbers(&file.lines, first_line);
        if anchor_lines.is_empty() {
            message.push_str("\napply_patch: first old-context line was not found anywhere");
        } else {
            message.push_str(&format!(
                "\napply_patch: first old-context line appears at current line(s): {}",
                anchor_lines
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
    }
    let context_center = context_center
        .or_else(|| {
            candidate_lines
                .first()
                .and_then(|line| line.checked_sub(1))
                .or_else(|| {
                    hunk.old
                        .first()
                        .and_then(|line| {
                            apply_patch_anchor_line_numbers(&file.lines, line)
                                .first()
                                .copied()
                        })
                        .and_then(|line| line.checked_sub(1))
                })
        })
        .or_else(|| (!file.lines.is_empty()).then_some(0));
    if let Some(center) = context_center
        && let Some((start, end)) = apply_patch_current_context_range(file, center)
    {
        message.push_str(
            "\napply_patch: suggested_next_step=reread_region\
             \napply_patch: retry_without_reread=false",
        );
        message.push_str(&format!(
            "\napply_patch: suggested_read_range={path}:{start}-{end}"
        ));
    } else {
        message.push_str(
            "\napply_patch: suggested_next_step=reread_target_file\
             \napply_patch: retry_without_reread=false",
        );
    }
    if let Some(center) = context_center {
        message.push_str(&apply_patch_current_context_message(file, center));
    }
    message.push_str("\napply_patch: failed old context follows:");
    for line in hunk.old.iter().take(APPLY_PATCH_MISMATCH_CONTEXT_LINES) {
        message.push_str("\napply_patch:   ");
        message.push_str(&apply_patch_mismatch_excerpt(line));
    }
    if hunk.old.len() > APPLY_PATCH_MISMATCH_CONTEXT_LINES {
        message.push_str(&format!(
            "\napply_patch:   ... ({} more old-context lines omitted)",
            hunk.old.len() - APPLY_PATCH_MISMATCH_CONTEXT_LINES
        ));
    }
    message.push_str(&format!(
        "\napply_patch: next step: read {path} around the reported line(s), then retry with a smaller fresh Mezzanine patch using a distinctive @@ header anchor"
    ));
    message.push_str(
        "\napply_patch: do not retry substantially the same patch without fresh target context",
    );
    super::MezError::invalid_args(message)
}

fn apply_patch_match_attempts_summary(attempts: &[ApplyPatchMatchAttempt]) -> String {
    attempts
        .iter()
        .map(|attempt| {
            let count = if attempt.capped {
                format!(">={}", attempt.candidate_count)
            } else {
                attempt.candidate_count.to_string()
            };
            format!("{}:{count}", attempt.mode.as_str())
        })
        .collect::<Vec<_>>()
        .join(",")
}

const APPLY_PATCH_MISMATCH_CONTEXT_LINES: usize = 8;
const APPLY_PATCH_MISMATCH_LINE_CHARS: usize = 160;
const APPLY_PATCH_MISMATCH_ANCHOR_LIMIT: usize = 5;
const APPLY_PATCH_MATCH_CANDIDATE_LIMIT: usize = 8;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ApplyPatchMatchMode {
    Exact,
    TrimEnd,
    Trim,
    Normalized,
}

impl ApplyPatchMatchMode {
    fn as_str(self) -> &'static str {
        match self {
            ApplyPatchMatchMode::Exact => "exact",
            ApplyPatchMatchMode::TrimEnd => "trim_end",
            ApplyPatchMatchMode::Trim => "trim",
            ApplyPatchMatchMode::Normalized => "normalized",
        }
    }
}

const APPLY_PATCH_MATCH_MODES: &[ApplyPatchMatchMode] = &[
    ApplyPatchMatchMode::Exact,
    ApplyPatchMatchMode::TrimEnd,
    ApplyPatchMatchMode::Trim,
    ApplyPatchMatchMode::Normalized,
];

#[derive(Debug, Clone, PartialEq, Eq)]
struct ApplyPatchHunkMatch {
    position: usize,
    mode: ApplyPatchMatchMode,
    old_line_offsets: Vec<usize>,
}

impl ApplyPatchHunkMatch {
    fn exact(position: usize, old_line_count: usize, mode: ApplyPatchMatchMode) -> Self {
        Self {
            position,
            mode,
            old_line_offsets: (0..old_line_count).collect(),
        }
    }

    fn span_len(&self) -> usize {
        self.old_line_offsets
            .last()
            .map(|offset| offset.saturating_add(1))
            .unwrap_or(0)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ApplyPatchLineSequenceMatch {
    position: usize,
    old_line_offsets: Vec<usize>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ApplyPatchMatchAttempt {
    mode: ApplyPatchMatchMode,
    candidate_count: usize,
    capped: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ApplyPatchCandidateMatches {
    lines: Vec<usize>,
    capped: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ApplyPatchLineSequenceMatches {
    lines: Vec<ApplyPatchLineSequenceMatch>,
    capped: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum ApplyPatchHunkMatchProblem {
    Missing {
        context_center: Option<usize>,
        missing_anchor: Option<String>,
        attempts: Vec<ApplyPatchMatchAttempt>,
    },
    Ambiguous {
        candidate_lines: Vec<usize>,
        mode: Option<ApplyPatchMatchMode>,
        attempts: Vec<ApplyPatchMatchAttempt>,
    },
}

fn find_hunk_position(
    file: &ApplyPatchTextFile,
    hunk: &MezPatchHunk,
    cursor: usize,
) -> std::result::Result<ApplyPatchHunkMatch, ApplyPatchHunkMatchProblem> {
    if hunk.anchors.is_empty() {
        return find_unanchored_hunk_position(
            &file.lines,
            &hunk.old,
            &hunk.old_line_gap_policies(),
            cursor,
            hunk.range_hint,
        );
    }

    let chains = ordered_anchor_chains(&file.lines, &hunk.anchors, cursor);
    if chains.is_empty() {
        return Err(ApplyPatchHunkMatchProblem::Missing {
            context_center: None,
            missing_anchor: first_missing_ordered_anchor(&file.lines, &hunk.anchors, cursor),
            attempts: Vec::new(),
        });
    }

    if hunk.old.is_empty() {
        if chains.len() == 1 {
            return Ok(ApplyPatchHunkMatch {
                position: chains[0]
                    .last()
                    .copied()
                    .map(|line| (line + 1).min(file.lines.len()))
                    .unwrap_or_else(|| cursor.min(file.lines.len())),
                mode: ApplyPatchMatchMode::Exact,
                old_line_offsets: Vec::new(),
            });
        }
        return Err(ApplyPatchHunkMatchProblem::Ambiguous {
            candidate_lines: chains
                .iter()
                .filter_map(|chain| chain.last())
                .map(|line| line + 2)
                .take(APPLY_PATCH_MATCH_CANDIDATE_LIMIT)
                .collect(),
            mode: None,
            attempts: Vec::new(),
        });
    }

    let mut ranges = Vec::new();
    for (chain_index, chain) in chains.iter().enumerate() {
        let search_start = chain.first().copied().unwrap_or(cursor);
        let search_end = chains
            .get(chain_index + 1)
            .and_then(|next| next.first().copied())
            .unwrap_or(file.lines.len());
        ranges.push((search_start, search_end));
    }
    find_hunk_position_in_ranges(
        &file.lines,
        &hunk.old,
        &hunk.old_line_gap_policies(),
        &ranges,
        hunk.range_hint,
    )
    .map_err(|failure| match failure {
        ApplyPatchLineSequenceFailure::Missing { attempts } => {
            ApplyPatchHunkMatchProblem::Missing {
                context_center: chains.first().and_then(|chain| chain.last()).copied(),
                missing_anchor: None,
                attempts,
            }
        }
        ApplyPatchLineSequenceFailure::Ambiguous {
            candidate_lines,
            mode,
            attempts,
        } => ApplyPatchHunkMatchProblem::Ambiguous {
            candidate_lines,
            mode: Some(mode),
            attempts,
        },
    })
}

fn find_unanchored_hunk_position(
    lines: &[String],
    old: &[String],
    blank_gap_policies: &[ApplyPatchBlankGapPolicy],
    cursor: usize,
    range_hint: Option<MezPatchRangeHint>,
) -> std::result::Result<ApplyPatchHunkMatch, ApplyPatchHunkMatchProblem> {
    if old.is_empty() {
        return Ok(ApplyPatchHunkMatch {
            position: apply_patch_preferred_position(range_hint, lines.len())
                .unwrap_or(lines.len()),
            mode: ApplyPatchMatchMode::Exact,
            old_line_offsets: Vec::new(),
        });
    }
    find_unanchored_hunk_position_layered(lines, old, blank_gap_policies, cursor, range_hint)
        .map_err(|failure| match failure {
            ApplyPatchLineSequenceFailure::Missing { attempts } => {
                ApplyPatchHunkMatchProblem::Missing {
                    context_center: old.first().and_then(|line| {
                        apply_patch_anchor_line_numbers(lines, line)
                            .first()
                            .and_then(|line| line.checked_sub(1))
                    }),
                    missing_anchor: None,
                    attempts,
                }
            }
            ApplyPatchLineSequenceFailure::Ambiguous {
                candidate_lines,
                mode,
                attempts,
            } => ApplyPatchHunkMatchProblem::Ambiguous {
                candidate_lines,
                mode: Some(mode),
                attempts,
            },
        })
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum ApplyPatchLineSequenceFailure {
    Missing {
        attempts: Vec<ApplyPatchMatchAttempt>,
    },
    Ambiguous {
        candidate_lines: Vec<usize>,
        mode: ApplyPatchMatchMode,
        attempts: Vec<ApplyPatchMatchAttempt>,
    },
}

fn find_hunk_position_in_ranges(
    lines: &[String],
    old: &[String],
    blank_gap_policies: &[ApplyPatchBlankGapPolicy],
    ranges: &[(usize, usize)],
    range_hint: Option<MezPatchRangeHint>,
) -> std::result::Result<ApplyPatchHunkMatch, ApplyPatchLineSequenceFailure> {
    let mut attempts = Vec::new();
    let preferred = apply_patch_preferred_position(range_hint, lines.len());
    for mode in APPLY_PATCH_MATCH_MODES {
        if let Some(position) = preferred {
            let position_matches_range = ranges.iter().any(|(start, end)| {
                position >= *start
                    && old
                        .len()
                        .checked_add(position)
                        .is_some_and(|needle_end| needle_end <= *end)
            });
            if position_matches_range
                && old
                    .len()
                    .checked_add(position)
                    .is_some_and(|needle_end| needle_end <= lines.len())
                && line_sequence_matches(&lines[position..position + old.len()], old, *mode)
            {
                return Ok(ApplyPatchHunkMatch::exact(position, old.len(), *mode));
            }
            for (start, end) in ranges {
                if position >= *start
                    && position < *end
                    && let Some(match_result) = line_sequence_match_omitting_blank_context_at(
                        lines,
                        old,
                        blank_gap_policies,
                        position,
                        *end,
                        *mode,
                    )
                {
                    return Ok(ApplyPatchHunkMatch {
                        position: match_result.position,
                        mode: *mode,
                        old_line_offsets: match_result.old_line_offsets,
                    });
                }
            }
        }
        let mut candidates = Vec::new();
        let mut capped = false;
        for (start, end) in ranges {
            let matches = find_line_sequence_matches(lines, old, *start, *end, *mode);
            capped |= matches.capped;
            candidates.extend(matches.lines);
            if candidates.len() >= APPLY_PATCH_MATCH_CANDIDATE_LIMIT {
                candidates.truncate(APPLY_PATCH_MATCH_CANDIDATE_LIMIT);
                capped = true;
                break;
            }
        }
        attempts.push(ApplyPatchMatchAttempt {
            mode: *mode,
            candidate_count: candidates.len(),
            capped,
        });
        match candidates.len() {
            0 => {}
            1 => {
                return Ok(ApplyPatchHunkMatch::exact(candidates[0], old.len(), *mode));
            }
            _ => {
                return Err(ApplyPatchLineSequenceFailure::Ambiguous {
                    candidate_lines: candidates.iter().map(|line| line + 1).collect(),
                    mode: *mode,
                    attempts,
                });
            }
        }
        let tolerant_matches = find_line_sequence_matches_omitting_blank_context(
            lines,
            old,
            blank_gap_policies,
            ranges,
            *mode,
        );
        if !tolerant_matches.lines.is_empty() {
            attempts.push(ApplyPatchMatchAttempt {
                mode: *mode,
                candidate_count: tolerant_matches.lines.len(),
                capped: tolerant_matches.capped,
            });
        }
        match tolerant_matches.lines.len() {
            0 => {}
            1 => {
                let match_result = tolerant_matches.lines.into_iter().next().unwrap();
                return Ok(ApplyPatchHunkMatch {
                    position: match_result.position,
                    mode: *mode,
                    old_line_offsets: match_result.old_line_offsets,
                });
            }
            _ => {
                return Err(ApplyPatchLineSequenceFailure::Ambiguous {
                    candidate_lines: tolerant_matches
                        .lines
                        .iter()
                        .map(|match_result| match_result.position + 1)
                        .collect(),
                    mode: *mode,
                    attempts,
                });
            }
        }
    }
    Err(ApplyPatchLineSequenceFailure::Missing { attempts })
}

fn find_unanchored_hunk_position_layered(
    lines: &[String],
    old: &[String],
    blank_gap_policies: &[ApplyPatchBlankGapPolicy],
    cursor: usize,
    range_hint: Option<MezPatchRangeHint>,
) -> std::result::Result<ApplyPatchHunkMatch, ApplyPatchLineSequenceFailure> {
    let mut attempts = Vec::new();
    let preferred = apply_patch_preferred_position(range_hint, lines.len())
        .filter(|position| *position >= cursor.min(lines.len()));
    for mode in APPLY_PATCH_MATCH_MODES {
        if let Some(position) = preferred
            && old
                .len()
                .checked_add(position)
                .is_some_and(|needle_end| needle_end <= lines.len())
            && line_sequence_matches(&lines[position..position + old.len()], old, *mode)
        {
            return Ok(ApplyPatchHunkMatch::exact(position, old.len(), *mode));
        }
        if let Some(position) = preferred
            && let Some(match_result) = line_sequence_match_omitting_blank_context_at(
                lines,
                old,
                blank_gap_policies,
                position,
                lines.len(),
                *mode,
            )
        {
            return Ok(ApplyPatchHunkMatch {
                position: match_result.position,
                mode: *mode,
                old_line_offsets: match_result.old_line_offsets,
            });
        }
        let mut matches = find_line_sequence_matches(lines, old, cursor, lines.len(), *mode);
        if matches.lines.is_empty() && cursor > 0 {
            matches = find_line_sequence_matches(lines, old, 0, lines.len(), *mode);
        }
        attempts.push(ApplyPatchMatchAttempt {
            mode: *mode,
            candidate_count: matches.lines.len(),
            capped: matches.capped,
        });
        match matches.lines.len() {
            0 => {}
            1 => {
                return Ok(ApplyPatchHunkMatch::exact(
                    matches.lines[0],
                    old.len(),
                    *mode,
                ));
            }
            _ => {
                return Err(ApplyPatchLineSequenceFailure::Ambiguous {
                    candidate_lines: matches.lines.iter().map(|line| line + 1).collect(),
                    mode: *mode,
                    attempts,
                });
            }
        }
        let tolerant_matches = find_line_sequence_matches_omitting_blank_context(
            lines,
            old,
            blank_gap_policies,
            &[(cursor.min(lines.len()), lines.len())],
            *mode,
        );
        if !tolerant_matches.lines.is_empty() {
            attempts.push(ApplyPatchMatchAttempt {
                mode: *mode,
                candidate_count: tolerant_matches.lines.len(),
                capped: tolerant_matches.capped,
            });
        }
        match tolerant_matches.lines.len() {
            0 => {}
            1 => {
                let match_result = tolerant_matches.lines.into_iter().next().unwrap();
                return Ok(ApplyPatchHunkMatch {
                    position: match_result.position,
                    mode: *mode,
                    old_line_offsets: match_result.old_line_offsets,
                });
            }
            _ => {
                return Err(ApplyPatchLineSequenceFailure::Ambiguous {
                    candidate_lines: tolerant_matches
                        .lines
                        .iter()
                        .map(|match_result| match_result.position + 1)
                        .collect(),
                    mode: *mode,
                    attempts,
                });
            }
        }
    }
    Err(ApplyPatchLineSequenceFailure::Missing { attempts })
}

fn apply_patch_preferred_position(
    range_hint: Option<MezPatchRangeHint>,
    line_count: usize,
) -> Option<usize> {
    range_hint.map(|hint| hint.old_start.saturating_sub(1).min(line_count))
}

fn ordered_anchor_chains(lines: &[String], anchors: &[String], cursor: usize) -> Vec<Vec<usize>> {
    if anchors.is_empty() {
        return vec![Vec::new()];
    }

    let mut chains = Vec::new();
    for (index, line) in lines.iter().enumerate().skip(cursor.min(lines.len())) {
        if !line.contains(&anchors[0]) {
            continue;
        }
        let mut chain = vec![index];
        let mut next_start = index + 1;
        let mut complete = true;
        for anchor in &anchors[1..] {
            if let Some((next_index, _)) = lines
                .iter()
                .enumerate()
                .skip(next_start)
                .find(|(_, line)| line.contains(anchor))
            {
                chain.push(next_index);
                next_start = next_index + 1;
            } else {
                complete = false;
                break;
            }
        }
        if complete {
            chains.push(chain);
            if chains.len() >= APPLY_PATCH_MATCH_CANDIDATE_LIMIT {
                break;
            }
        }
    }
    chains
}

fn first_missing_ordered_anchor(
    lines: &[String],
    anchors: &[String],
    cursor: usize,
) -> Option<String> {
    let mut next_start = cursor.min(lines.len());
    for anchor in anchors {
        if let Some((next_index, _)) = lines
            .iter()
            .enumerate()
            .skip(next_start)
            .find(|(_, line)| line.contains(anchor))
        {
            next_start = next_index + 1;
        } else {
            return Some(anchor.clone());
        }
    }
    None
}

fn find_line_sequence_matches(
    lines: &[String],
    needle: &[String],
    start: usize,
    end: usize,
    mode: ApplyPatchMatchMode,
) -> ApplyPatchCandidateMatches {
    if needle.is_empty() {
        return ApplyPatchCandidateMatches {
            lines: vec![start.min(lines.len())],
            capped: false,
        };
    }
    let start = start.min(lines.len());
    let end = end.min(lines.len());
    if end < start || end.saturating_sub(start) < needle.len() {
        return ApplyPatchCandidateMatches {
            lines: Vec::new(),
            capped: false,
        };
    }
    let last_start = end - needle.len();
    let mut matches = Vec::new();
    let mut capped = false;
    for index in start..=last_start {
        if line_sequence_matches(&lines[index..index + needle.len()], needle, mode) {
            matches.push(index);
            if matches.len() >= APPLY_PATCH_MATCH_CANDIDATE_LIMIT {
                capped = true;
                break;
            }
        }
    }
    ApplyPatchCandidateMatches {
        lines: matches,
        capped,
    }
}

fn find_line_sequence_matches_omitting_blank_context(
    lines: &[String],
    needle: &[String],
    blank_gap_policies: &[ApplyPatchBlankGapPolicy],
    ranges: &[(usize, usize)],
    mode: ApplyPatchMatchMode,
) -> ApplyPatchLineSequenceMatches {
    if !blank_gap_policies
        .iter()
        .any(|policy| *policy != ApplyPatchBlankGapPolicy::Disallow)
        || blank_gap_policies.len() != needle.len()
    {
        return ApplyPatchLineSequenceMatches {
            lines: Vec::new(),
            capped: false,
        };
    }
    let mut matches = Vec::new();
    let mut capped = false;
    for (start, end) in ranges {
        let start = (*start).min(lines.len());
        let end = (*end).min(lines.len());
        if end < start {
            continue;
        }
        for index in start..end {
            if let Some(match_result) = line_sequence_match_omitting_blank_context_at(
                lines,
                needle,
                blank_gap_policies,
                index,
                end,
                mode,
            ) {
                matches.push(match_result);
                if matches.len() >= APPLY_PATCH_MATCH_CANDIDATE_LIMIT {
                    capped = true;
                    return ApplyPatchLineSequenceMatches {
                        lines: matches,
                        capped,
                    };
                }
            }
        }
    }
    ApplyPatchLineSequenceMatches {
        lines: matches,
        capped,
    }
}

fn line_sequence_match_omitting_blank_context_at(
    lines: &[String],
    needle: &[String],
    blank_gap_policies: &[ApplyPatchBlankGapPolicy],
    position: usize,
    end: usize,
    mode: ApplyPatchMatchMode,
) -> Option<ApplyPatchLineSequenceMatch> {
    if needle.is_empty()
        || blank_gap_policies.len() != needle.len()
        || !blank_gap_policies
            .iter()
            .any(|policy| *policy != ApplyPatchBlankGapPolicy::Disallow)
    {
        return None;
    }
    let end = end.min(lines.len());
    if position >= end {
        return None;
    }
    let mut actual_index = position;
    let mut old_line_offsets = Vec::with_capacity(needle.len());
    let mut skipped_blank = false;
    for (needle_index, expected) in needle.iter().enumerate() {
        if actual_index >= end {
            return None;
        }
        if patch_line_matches(&lines[actual_index], expected, mode) {
            old_line_offsets.push(actual_index.saturating_sub(position));
            actual_index += 1;
            continue;
        }
        if blank_gap_policies[needle_index] == ApplyPatchBlankGapPolicy::Disallow {
            return None;
        }
        let blank_start = actual_index;
        while actual_index < end && lines[actual_index].trim().is_empty() {
            actual_index += 1;
        }
        if actual_index == blank_start || actual_index >= end {
            return None;
        }
        if !patch_line_matches(&lines[actual_index], expected, mode) {
            return None;
        }
        skipped_blank = true;
        old_line_offsets.push(actual_index.saturating_sub(position));
        actual_index += 1;
    }
    skipped_blank.then_some(ApplyPatchLineSequenceMatch {
        position,
        old_line_offsets,
    })
}

fn line_sequence_matches(
    actual: &[String],
    expected: &[String],
    mode: ApplyPatchMatchMode,
) -> bool {
    actual.len() == expected.len()
        && actual
            .iter()
            .zip(expected)
            .all(|(actual, expected)| patch_line_matches(actual, expected, mode))
}

fn patch_line_matches(actual: &str, expected: &str, mode: ApplyPatchMatchMode) -> bool {
    match mode {
        ApplyPatchMatchMode::Exact => actual == expected,
        ApplyPatchMatchMode::TrimEnd => actual.trim_end() == expected.trim_end(),
        ApplyPatchMatchMode::Trim => actual.trim() == expected.trim(),
        ApplyPatchMatchMode::Normalized => {
            normalized_patch_line(actual) == normalized_patch_line(expected)
        }
    }
}

fn normalized_patch_line(line: &str) -> String {
    line.trim()
        .chars()
        .map(|character| match character {
            '\u{2010}' | '\u{2011}' | '\u{2012}' | '\u{2013}' | '\u{2014}' | '\u{2015}'
            | '\u{2212}' => '-',
            '\u{2018}' | '\u{2019}' | '\u{201A}' | '\u{201B}' => '\'',
            '\u{201C}' | '\u{201D}' | '\u{201E}' | '\u{201F}' => '"',
            '\u{00A0}' | '\u{2002}' | '\u{2003}' | '\u{2004}' | '\u{2005}' | '\u{2006}'
            | '\u{2007}' | '\u{2008}' | '\u{2009}' | '\u{200A}' | '\u{202F}' | '\u{205F}'
            | '\u{3000}' => ' ',
            other => other,
        })
        .collect()
}

fn apply_patch_anchor_line_numbers(lines: &[String], anchor: &str) -> Vec<usize> {
    lines
        .iter()
        .enumerate()
        .filter_map(|(index, line)| (line == anchor).then_some(index + 1))
        .take(APPLY_PATCH_MISMATCH_ANCHOR_LIMIT)
        .collect()
}

fn apply_patch_mismatch_excerpt(line: &str) -> String {
    let mut excerpt: String = line.chars().take(APPLY_PATCH_MISMATCH_LINE_CHARS).collect();
    if line.chars().count() > APPLY_PATCH_MISMATCH_LINE_CHARS {
        excerpt.push_str("...");
    }
    excerpt
}

fn apply_patch_current_context_message(file: &ApplyPatchTextFile, center: usize) -> String {
    if file.lines.is_empty() {
        return "\napply_patch: current file is empty".to_string();
    }
    let Some((start_line, end_line)) = apply_patch_current_context_range(file, center) else {
        return "\napply_patch: current file is empty".to_string();
    };
    let mut message = format!(
        "\napply_patch: current file context near line {} follows:",
        center + 1
    );
    for index in start_line.saturating_sub(1)..end_line {
        message.push_str(&format!(
            "\napply_patch:   {:>4}: {}",
            index + 1,
            apply_patch_mismatch_excerpt(&file.lines[index])
        ));
    }
    message
}

fn apply_patch_current_context_range(
    file: &ApplyPatchTextFile,
    center: usize,
) -> Option<(usize, usize)> {
    if file.lines.is_empty() {
        return None;
    }
    let start = center.saturating_sub(APPLY_PATCH_MISMATCH_CONTEXT_LINES / 2);
    let end = (center + (APPLY_PATCH_MISMATCH_CONTEXT_LINES / 2) + 1).min(file.lines.len());
    Some((start + 1, end))
}

fn snapshot_text_state(snapshot: &ApplyPatchSnapshot) -> Result<Option<ApplyPatchTextFile>> {
    match &snapshot.state {
        ApplyPatchSnapshotState::Regular(bytes) => {
            Ok(Some(ApplyPatchTextFile::from_bytes(&snapshot.path, bytes)?))
        }
        ApplyPatchSnapshotState::Missing => Ok(None),
        ApplyPatchSnapshotState::NonRegular => Err(super::MezError::invalid_args(format!(
            "apply_patch: refusing to patch non-regular file: {}",
            snapshot.path
        ))),
        ApplyPatchSnapshotState::OutsideCwd => Err(super::MezError::invalid_args(format!(
            "apply_patch: resolved path is outside current working directory: {}",
            snapshot.path
        ))),
        ApplyPatchSnapshotState::Error => Err(super::MezError::invalid_args(format!(
            "apply_patch: failed to resolve path: {}",
            snapshot.path
        ))),
    }
}

fn ensure_missing_state(path: &str, state: Option<&Option<ApplyPatchTextFile>>) -> Result<()> {
    match state {
        Some(None) => Ok(()),
        Some(Some(_)) => Err(super::MezError::invalid_args(format!(
            "apply_patch: refusing to add existing path: {path}"
        ))),
        None => Err(super::MezError::invalid_args(format!(
            "apply_patch: missing remote snapshot for path: {path}"
        ))),
    }
}

fn ensure_regular_state<'a>(
    path: &str,
    state: Option<&'a Option<ApplyPatchTextFile>>,
) -> Result<&'a ApplyPatchTextFile> {
    match state {
        Some(Some(file)) => Ok(file),
        Some(None) => Err(super::MezError::invalid_args(format!(
            "apply_patch: missing file: {path}"
        ))),
        None => Err(super::MezError::invalid_args(format!(
            "apply_patch: missing remote snapshot for path: {path}"
        ))),
    }
}
