//! Shared error types.
//!
//! Errors carry a stable kind for tests and callers plus a human-readable
//! diagnostic message. This avoids string-only control flow while keeping error
//! display and trait behavior generated by `thiserror`.

use std::io;

use thiserror::Error;

/// Defines the Result type used by this subsystem.
///
/// Keeping this value documented makes the contract explicit at the module
/// boundary and avoids relying on call-site inference.
pub type Result<T> = std::result::Result<T, MezError>;

impl From<MezErrorKind> for mez_agent::ProviderErrorKind {
    fn from(kind: MezErrorKind) -> Self {
        match kind {
            MezErrorKind::InvalidArgs => Self::InvalidArgs,
            MezErrorKind::InvalidState => Self::InvalidState,
            MezErrorKind::Config => Self::Config,
            MezErrorKind::Io => Self::Io,
            MezErrorKind::Conflict => Self::Conflict,
            MezErrorKind::NotFound => Self::NotFound,
            MezErrorKind::Forbidden => Self::Forbidden,
            MezErrorKind::NotImplemented => Self::NotImplemented,
        }
    }
}

impl From<mez_agent::ProviderErrorKind> for MezErrorKind {
    fn from(kind: mez_agent::ProviderErrorKind) -> Self {
        match kind {
            mez_agent::ProviderErrorKind::InvalidArgs => Self::InvalidArgs,
            mez_agent::ProviderErrorKind::InvalidState => Self::InvalidState,
            mez_agent::ProviderErrorKind::Config => Self::Config,
            mez_agent::ProviderErrorKind::Io => Self::Io,
            mez_agent::ProviderErrorKind::Conflict => Self::Conflict,
            mez_agent::ProviderErrorKind::NotFound => Self::NotFound,
            mez_agent::ProviderErrorKind::Forbidden => Self::Forbidden,
            mez_agent::ProviderErrorKind::NotImplemented => Self::NotImplemented,
        }
    }
}

impl From<mez_agent::SchedulerError> for MezError {
    fn from(error: mez_agent::SchedulerError) -> Self {
        match error.kind() {
            mez_agent::SchedulerErrorKind::InvalidArgs => Self::invalid_args(error.message()),
            mez_agent::SchedulerErrorKind::InvalidState => Self::invalid_state(error.message()),
            mez_agent::SchedulerErrorKind::Conflict => Self::conflict(error.message()),
            mez_agent::SchedulerErrorKind::NotFound => {
                Self::new(MezErrorKind::NotFound, error.message())
            }
        }
    }
}

impl From<mez_mux::MuxError> for MezError {
    fn from(error: mez_mux::MuxError) -> Self {
        match error.kind() {
            mez_mux::MuxErrorKind::InvalidArgs => Self::invalid_args(error.message()),
            mez_mux::MuxErrorKind::InvalidState => Self::invalid_state(error.message()),
            mez_mux::MuxErrorKind::Conflict => Self::conflict(error.message()),
            mez_mux::MuxErrorKind::NotFound => Self::new(MezErrorKind::NotFound, error.message()),
            mez_mux::MuxErrorKind::Forbidden => Self::forbidden(error.message()),
            mez_mux::MuxErrorKind::Io => Self::new(MezErrorKind::Io, error.message()),
        }
    }
}

impl From<mez_terminal::TerminalSizeError> for MezError {
    fn from(error: mez_terminal::TerminalSizeError) -> Self {
        Self::invalid_args(error.message())
    }
}

impl From<mez_terminal::TerminalScreenConfigError> for MezError {
    fn from(error: mez_terminal::TerminalScreenConfigError) -> Self {
        Self::invalid_args(error.message())
    }
}

/// Carries Mez Error Kind state for this subsystem.
///
/// The type keeps related data explicit so callers can inspect and move
/// structured runtime state without parsing display text.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MezErrorKind {
    /// Represents the Invalid Args case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    InvalidArgs,
    /// Represents the Invalid State case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    InvalidState,
    /// Represents the Config case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    Config,
    /// Represents the Io case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    Io,
    /// Represents the Conflict case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    Conflict,
    /// Represents the Not Found case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    NotFound,
    /// Represents the Forbidden case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    Forbidden,
    /// Represents the Not Implemented case for this enumeration.
    ///
    /// Callers use this variant to describe one explicit state or command path
    /// without relying on stringly typed status values.
    NotImplemented,
}

/// Carries Mez Error state for this subsystem.
///
/// The type keeps related data explicit so callers can inspect and move
/// structured runtime state without parsing display text.
#[derive(Debug, Error)]
#[error("{kind:?}: {message}")]
pub struct MezError {
    /// Stores the kind value for this data structure.
    ///
    /// The field is part of structured state exchanged across this module
    /// boundary and should remain aligned with the owning type invariant.
    kind: MezErrorKind,
    /// Stores the message value for this data structure.
    ///
    /// The field is part of structured state exchanged across this module
    /// boundary and should remain aligned with the owning type invariant.
    message: String,
    /// Stores the io kind value for this data structure.
    ///
    /// The field is part of structured state exchanged across this module
    /// boundary and should remain aligned with the owning type invariant.
    io_kind: Option<io::ErrorKind>,
    /// Stores the provider raw text value for this data structure.
    ///
    /// The field is part of structured state exchanged across this module
    /// boundary and should remain aligned with the owning type invariant.
    provider_raw_text: Option<String>,
    /// Stores the provider failure json value for this data structure.
    ///
    /// The field is part of structured state exchanged across this module
    /// boundary and should remain aligned with the owning type invariant.
    provider_failure_json: Option<String>,
}

impl MezError {
    /// Runs the new operation for this subsystem.
    ///
    /// The function keeps parsing, state changes, and error propagation in
    /// the owning module so callers receive typed results instead of relying
    /// on duplicated control-flow logic.
    pub fn new(kind: MezErrorKind, message: impl Into<String>) -> Self {
        Self {
            kind,
            message: message.into(),
            io_kind: None,
            provider_raw_text: None,
            provider_failure_json: None,
        }
    }

    /// Runs the invalid args operation for this subsystem.
    ///
    /// The function keeps parsing, state changes, and error propagation in
    /// the owning module so callers receive typed results instead of relying
    /// on duplicated control-flow logic.
    pub fn invalid_args(message: impl Into<String>) -> Self {
        Self::new(MezErrorKind::InvalidArgs, message)
    }

    /// Runs the invalid state operation for this subsystem.
    ///
    /// The function keeps parsing, state changes, and error propagation in
    /// the owning module so callers receive typed results instead of relying
    /// on duplicated control-flow logic.
    pub fn invalid_state(message: impl Into<String>) -> Self {
        Self::new(MezErrorKind::InvalidState, message)
    }

    /// Runs the config operation for this subsystem.
    ///
    /// The function keeps parsing, state changes, and error propagation in
    /// the owning module so callers receive typed results instead of relying
    /// on duplicated control-flow logic.
    pub fn config(message: impl Into<String>) -> Self {
        Self::new(MezErrorKind::Config, message)
    }

    /// Runs the conflict operation for this subsystem.
    ///
    /// The function keeps parsing, state changes, and error propagation in
    /// the owning module so callers receive typed results instead of relying
    /// on duplicated control-flow logic.
    pub fn conflict(message: impl Into<String>) -> Self {
        Self::new(MezErrorKind::Conflict, message)
    }

    /// Runs the forbidden operation for this subsystem.
    ///
    /// The function keeps parsing, state changes, and error propagation in
    /// the owning module so callers receive typed results instead of relying
    /// on duplicated control-flow logic.
    pub fn forbidden(message: impl Into<String>) -> Self {
        Self::new(MezErrorKind::Forbidden, message)
    }

    /// Runs the not implemented operation for this subsystem.
    ///
    /// The function keeps parsing, state changes, and error propagation in
    /// the owning module so callers receive typed results instead of relying
    /// on duplicated control-flow logic.
    pub fn not_implemented(message: impl Into<String>) -> Self {
        Self::new(MezErrorKind::NotImplemented, message)
    }

    /// Runs the kind operation for this subsystem.
    ///
    /// The function keeps parsing, state changes, and error propagation in
    /// the owning module so callers receive typed results instead of relying
    /// on duplicated control-flow logic.
    pub fn kind(&self) -> MezErrorKind {
        self.kind
    }

    /// Runs the message operation for this subsystem.
    ///
    /// The function keeps parsing, state changes, and error propagation in
    /// the owning module so callers receive typed results instead of relying
    /// on duplicated control-flow logic.
    pub fn message(&self) -> &str {
        &self.message
    }

    /// Returns the original stdlib I/O error kind when this error was converted
    /// from an `io::Error`.
    pub fn io_kind(&self) -> Option<io::ErrorKind> {
        self.io_kind
    }

    /// Attach raw provider response text that should be available to runtime
    /// transcript failure handling without changing the public error message.
    pub fn with_provider_raw_text(mut self, raw_text: impl Into<String>) -> Self {
        let raw_text = raw_text.into();
        if !raw_text.is_empty() {
            self.provider_raw_text = Some(raw_text);
        }
        self
    }

    /// Return raw provider response text attached to this error, when present.
    pub fn provider_raw_text(&self) -> Option<&str> {
        self.provider_raw_text.as_deref()
    }

    /// Attach a structured provider failure object for audit diagnostics.
    ///
    /// Provider adapters use this for non-success API responses and stream
    /// failure events. It is intentionally separate from raw model output so the
    /// runtime can audit API errors without storing prompt or completion content.
    pub fn with_provider_failure_json(mut self, failure_json: impl Into<String>) -> Self {
        let failure_json = failure_json.into();
        if !failure_json.is_empty() {
            self.provider_failure_json = Some(failure_json);
        }
        self
    }

    /// Return the structured provider failure object, when one was attached.
    pub fn provider_failure_json(&self) -> Option<&str> {
        self.provider_failure_json.as_deref()
    }
}

impl From<io::Error> for MezError {
    /// Runs the from operation for this subsystem.
    ///
    /// The function keeps parsing, state changes, and error propagation in
    /// the owning module so callers receive typed results instead of relying
    /// on duplicated control-flow logic.
    fn from(error: io::Error) -> Self {
        Self {
            kind: MezErrorKind::Io,
            message: error.to_string(),
            io_kind: Some(error.kind()),
            provider_raw_text: None,
            provider_failure_json: None,
        }
    }
}

impl From<rusqlite::Error> for MezError {
    /// Converts SQLite persistence failures into Mezzanine I/O errors.
    ///
    /// Memory storage is local durable I/O, so callers receive the same broad
    /// error kind as filesystem persistence failures while retaining the
    /// SQLite diagnostic message.
    fn from(error: rusqlite::Error) -> Self {
        Self::new(MezErrorKind::Io, error.to_string())
    }
}
